#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2019/1-Hanfeng"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2019/1-Hanfeng
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + CH2CHO <=> HO2 + CH2CO""",
)

entry(
    index = 1,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + C2H5 <=> H2O2 + C2H4""",
)

entry(
    index = 2,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.8e+06,'cm^3/(mol*s)'), n=2.54, Ea=(6760,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + iC4H10 <=> H2 + iC4H9""",
)

entry(
    index = 3,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.36,'cm^3/(mol*s)'), n=3.65, Ea=(7150,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + iC4H10 <=> CH4 + iC4H9""",
)

