#!/usr/bin/env python
# encoding: utf-8

name = "PCI2017/025-Sudholt"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2017/025-Sudholt
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5 + HO2 <=> C2H4 + H2O2""",
)

entry(
    index = 1,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+10,'s^-1'), n=0, Ea=(20849.9,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is P-C4H9O2 <=> C4H8OOH1-3""",
)

entry(
    index = 2,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.6e+06,'cm^3/(mol*s)'), n=2.4, Ea=(4471.08,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H => S-C4H9 + H2""",
)

