name: kms
channels:
  - conda-forge
  - rmg
  - nodefaults
dependencies:
  - python=3.9
  - nomkl
  - cairo
  - cairocffi
  - xlrd
  - xlwt
  - habanero>=0.6,<0.7
  - rmg=3.3.0  # Available for linux-64 (x86_64)
  - django-filter
  - django-extensions
  - django-model-utils
  - django-crispy-forms
  - gunicorn
  - pip
  - pip:
    - django==3.0
    - titlecase
    - black
    - flake8
    - flake8-django
    - django-test-migrations
    - django-autocomplete-light
    - djangorestframework
    - drf-writable-nested
    - python-dotenv
    - pydantic
    - psycopg2-binary
