#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2013/2680-Vranckx"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2013/2680-Vranckx
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + C2H4 <=> C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5 + C2H4 => PC4H9""",
)

entry(
    index = 1,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.837,'cm^3/(mol*s)'), n=3.59, Ea=(11960,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9 + O2 <=> C4H8-1 + HO2""",
)

entry(
    index = 2,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.75e+10,'s^-1'), n=0, Ea=(24400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is SC4H9O2 => C4H8OOH2-4""",
)

entry(
    index = 3,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(188000,'cm^3/(mol*s)'), n=2.75, Ea=(6280,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H => PC4H9 + H2""",
)

entry(
    index = 4,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5 + HO2 <=> C2H4 + H2O2""",
)

entry(
    index = 5,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+11,'cm^3/(mol*s)'), n=0, Ea=(1840,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + O2 => CH2CO + HO2""",
)

entry(
    index = 6,
    label = "C4H9 + HO2 <=> O2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.53e+09,'cm^3/(mol*s)'), n=0.622, Ea=(-49,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is SC4H9 + HO2 => C4H10 + O2""",
)

entry(
    index = 7,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.904,'cm^3/(mol*s)'), n=3.65, Ea=(7150,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + CH3 => PC4H9 + CH4""",
)

entry(
    index = 8,
    label = "C4H9 + H2O2 -> HO2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5030,'cm^3/(mol*s)'), n=2.437, Ea=(3020,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9 + H2O2 => C4H10 + HO2""",
)

entry(
    index = 9,
    label = "CH4O2 + C4H9 -> CH3O2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(97900,'cm^3/(mol*s)'), n=1.992, Ea=(1430,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3O2H + PC4H9 => CH3O2 + C4H10""",
)

entry(
    index = 10,
    label = "C2H6O2 + C4H9 <=> C4H10 + C2H5O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(6500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5O2H + PC4H9 => C2H5O2 + C4H10""",
)

entry(
    index = 11,
    label = "C3H8O2 + C4H9 <=> C4H10 + C3H7O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(6500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is NC3H7O2H + SC4H9 => NC3H7O2 + C4H10""",
)

entry(
    index = 12,
    label = "C4H10O2 + C4H9 <=> C4H10 + C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(6500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9O2H + PC4H9 => PC4H9O2 + C4H10""",
)

