#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2013/1541-Zhang"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2013/1541-Zhang
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.904,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + CH3 <=> PC4H9 + CH4""",
)

entry(
    index = 1,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.6e+06,'cm^3/(mol*s)'), n=2.4, Ea=(4471,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H <=> SC4H9 + H2""",
)

entry(
    index = 2,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.837,'cm^3/(mol*s)'), n=3.59, Ea=(11960,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9 + O2 <=> C4H8-1 + HO2""",
)

entry(
    index = 3,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'s^-1'), n=0, Ea=(31850,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9O2 <=> C4H8OOH1-2""",
)

