# Generated by Django 4.2.24 on 2025-10-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this import job (hash of input files)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Name/path of the model being imported", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("species_file", models.TextField(blank=True)),
                ("reactions_file", models.TextField(blank=True)),
                ("thermo_file", models.TextField(blank=True)),
                ("total_species", models.IntegerField(default=0)),
                ("identified_species", models.IntegerField(default=0)),
                ("total_reactions", models.IntegerField(default=0)),
                ("matched_reactions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated this import",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemkin_label",
                    models.CharField(
                        db_index=True, help_text="Chemkin species label", max_length=255
                    ),
                ),
                (
                    "chemkin_formula",
                    models.CharField(
                        blank=True,
                        help_text="Chemical formula of the Chemkin species",
                        max_length=100,
                    ),
                ),
                ("rmg_species_label", models.CharField(max_length=255)),
                ("rmg_species_smiles", models.TextField()),
                ("rmg_species_index", models.IntegerField()),
                ("rmg_species_formula", models.CharField(blank=True, max_length=100)),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0, help_text="Number of reactions voting for this match"
                    ),
                ),
                (
                    "enthalpy_discrepancy",
                    models.FloatField(
                        blank=True, help_text="Enthalpy difference in kJ/mol at 298K", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence score for this match (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_votes",
                        to="import_voting.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "species_votes",
                "ordering": ["-vote_count", "chemkin_label"],
            },
        ),
        migrations.CreateModel(
            name="IdentifiedSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chemkin_label", models.CharField(db_index=True, max_length=255)),
                ("chemkin_formula", models.CharField(blank=True, max_length=100)),
                ("rmg_species_label", models.CharField(max_length=255)),
                ("rmg_species_smiles", models.TextField()),
                ("rmg_species_index", models.IntegerField(blank=True, null=True)),
                (
                    "identification_method",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("manual", "Manual"),
                            ("vote", "Voting System"),
                            ("thermo", "Thermo Library Match"),
                            ("formula", "Formula Match"),
                        ],
                        default="auto",
                        max_length=50,
                    ),
                ),
                (
                    "identified_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who confirmed the match",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "enthalpy_discrepancy",
                    models.FloatField(
                        blank=True, help_text="Enthalpy difference in kJ/mol at 298K", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("identified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identified_species_set",
                        to="import_voting.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "identified_species",
            },
        ),
        migrations.CreateModel(
            name="BlockedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chemkin_label", models.CharField(db_index=True, max_length=255)),
                ("rmg_species_label", models.CharField(max_length=255)),
                ("rmg_species_smiles", models.TextField()),
                ("rmg_species_index", models.IntegerField(blank=True, null=True)),
                (
                    "blocked_by",
                    models.CharField(
                        blank=True,
                        help_text="Username who blocked this match",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("blocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_matches",
                        to="import_voting.importjob",
                    ),
                ),
            ],
            options={
                "db_table": "blocked_matches",
            },
        ),
        migrations.CreateModel(
            name="VotingReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chemkin_reaction_str", models.TextField()),
                ("edge_reaction_str", models.TextField()),
                ("reaction_family", models.CharField(blank=True, max_length=255)),
                ("chemkin_reaction_json", models.JSONField(blank=True, null=True)),
                ("edge_reaction_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "species_vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_reactions",
                        to="import_voting.speciesvote",
                    ),
                ),
            ],
            options={
                "db_table": "voting_reactions",
                "indexes": [
                    models.Index(fields=["species_vote"], name="voting_reac_species_57ca9c_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="speciesvote",
            index=models.Index(
                fields=["import_job", "chemkin_label"], name="species_vot_import__8b4b99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="speciesvote",
            index=models.Index(
                fields=["import_job", "vote_count"], name="species_vot_import__b8e914_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="speciesvote",
            unique_together={("import_job", "chemkin_label", "rmg_species_index")},
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(fields=["job_id", "status"], name="import_jobs_job_id_ce599f_idx"),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["status", "-updated_at"], name="import_jobs_status_09cf44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identifiedspecies",
            index=models.Index(
                fields=["import_job", "chemkin_label"], name="identified__import__f3feea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identifiedspecies",
            index=models.Index(
                fields=["import_job", "identification_method"],
                name="identified__import__ccbe7c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="identifiedspecies",
            unique_together={("import_job", "chemkin_label")},
        ),
        migrations.AddIndex(
            model_name="blockedmatch",
            index=models.Index(
                fields=["import_job", "chemkin_label"], name="blocked_mat_import__986ac9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockedmatch",
            unique_together={("import_job", "chemkin_label", "rmg_species_index")},
        ),
    ]
