#!/usr/bin/env python
# encoding: utf-8

name = "PCI2015/0409-Zhang"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2015/0409-Zhang
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.33e+06,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H <=> pC4H9 + H2""",
)

entry(
    index = 1,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.906,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + CH3 <=> pC4H9 + CH4""",
)

