#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2013/487-Schenk"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2013/487-Schenk
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.5e+10,'s^-1'), n=0, Ea=(24400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is I-C4H9O2 <=> I-C4H8O2H-I""",
)

entry(
    index = 1,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.81e+11,'cm^3/(mol*s)'), n=0, Ea=(1840,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + O2 <=> HO2 + CH2CO""",
)

entry(
    index = 2,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+12,'cm^3/(mol*s)'), n=0, Ea=(2006,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H9-1 + O2 <=> HO2 + C4H8-1""",
)

entry(
    index = 3,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.63e+07,'cm^3/(mol*s)'), n=2, Ea=(7691,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + C4H10 => C4H9-1 + H2""",
)

entry(
    index = 4,
    label = "C4H9 + H2O2 -> HO2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.58e+12,'cm^3/(mol*s)'), n=0, Ea=(9817,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H2O2 + C4H9-1 => HO2 + C4H10""",
)

entry(
    index = 5,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+12,'cm^3/(mol*s)'), n=0, Ea=(11610,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + C4H10 => CH4 + C4H9-1""",
)

entry(
    index = 6,
    label = "C4H9 + HO2 <=> O2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.07e+12,'cm^3/(mol*s)'), n=0, Ea=(-3630,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + C4H9-2 => C4H10 + O2""",
)

