#!/usr/bin/env python
# encoding: utf-8

name = "harris_butane"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 52,
    label = "O2(2) + [CH2]C=O <=> HO2(16) + C2H2O(603)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(7497.23,'cm^3/(mol*s)'), n=3.01959, Ea=(164.711,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.35462, dn = +|- 0.0398767, dEa = +|- 0.217008 kJ/mol"""),
)

entry(
    index = 213,
    label = "HO2(16) + C[CH2](20) <=> H2O2(17) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(50428.1,'cm^3/(mol*s)'), n=2.95925, Ea=(89.8944,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.15317, dn = +|- 0.0187231, dEa = +|- 0.101891 kJ/mol"""),
)

entry(
    index = 246,
    label = "H(14) + butane(1) <=> H2(13) + C[CH]CC(23)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.82209e+09,'cm^3/(mol*s)'), n=1.43712, Ea=(28.1064,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.02505, dn = +|- 0.00325047, dEa = +|- 0.0176889 kJ/mol"""),
)

entry(
    index = 278,
    label = "O2(2) + C[CH]CC(23) <=> HO2(16) + C4H8(46)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5484.9,'cm^3/(mol*s)'), n=3.03099, Ea=(197.302,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.19355, dn = +|- 0.0232454, dEa = +|- 0.126501 kJ/mol"""),
)

entry(
    index = 286,
    label = "[CH3](22) + butane(1) <=> CH4(10) + [CH2]CCC(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.30134e+06,'cm^3/(mol*s)'), n=2.37197, Ea=(55.4705,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.10478, dn = +|- 0.0130919, dEa = +|- 0.0712454 kJ/mol"""),
)

entry(
    index = 288,
    label = "OH(15) + butane(1) <=> H2O(8) + [CH2]CCC(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.94247e+07,'cm^3/(mol*s)'), n=2.12863, Ea=(10.4218,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05628, dn = +|- 0.00719307, dEa = +|- 0.0391444 kJ/mol"""),
)

entry(
    index = 289,
    label = "O(5) + butane(1) <=> OH(15) + [CH2]CCC(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.18515e+08,'cm^3/(mol*s)'), n=2.12848, Ea=(29.2067,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.16963, dn = +|- 0.0205853, dEa = +|- 0.112024 kJ/mol"""),
)

entry(
    index = 313,
    label = "O2(2) + [CH2]CCC(24) <=> HO2(16) + C4H8(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.39521,'cm^3/(mol*s)'), n=3.7951, Ea=(195.187,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.4954, dn = +|- 0.0528662, dEa = +|- 0.287696 kJ/mol"""),
)

entry(
    index = 314,
    label = "O2(2) + C[CH]CC(23) <=> HO2(16) + C4H8(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1553.6,'cm^3/(mol*s)'), n=3.18529, Ea=(210.187,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11964, dn = +|- 0.0148474, dEa = +|- 0.0807989 kJ/mol"""),
)

entry(
    index = 419,
    label = "HO2(16) + [CH2]C=O <=> H2O2(17) + C2H2O(603)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.18697,'cm^3/(mol*s)'), n=3.95303, Ea=(54.4986,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.45051, dn = +|- 0.0488621, dEa = +|- 0.265906 kJ/mol"""),
)

entry(
    index = 427,
    label = "[CH2]C=O + [CH2]C=O <=> C2H2O(603) + C2H4O(35)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(215.014,'cm^3/(mol*s)'), n=3.21591, Ea=(45.4901,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.31315, dn = +|- 0.0357921, dEa = +|- 0.194779 kJ/mol"""),
)

entry(
    index = 442,
    label = "[CH2]C=O + [CH2]CCC(24) <=> C2H4O(35) + C4H8(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.6571e-06,'cm^3/(mol*s)'), n=5.03507, Ea=(52.7998,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.37458, dn = +|- 0.0417987, dEa = +|- 0.227467 kJ/mol"""),
)

entry(
    index = 578,
    label = "[CH2]C=C + [CH2]CCC(24) <=> C3H6(12) + C4H8(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(292.142,'cm^3/(mol*s)'), n=3.2781, Ea=(96.0426,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.29581, dn = +|- 0.0340454, dEa = +|- 0.185274 kJ/mol"""),
)

entry(
    index = 581,
    label = "[CH2]C=O + [CH2]C=C <=> C2H2O(603) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(7789.5,'cm^3/(mol*s)'), n=2.98694, Ea=(78.2597,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0665, dn = +|- 0.00845848, dEa = +|- 0.0460307 kJ/mol"""),
)

entry(
    index = 808,
    label = "C[CH]CC(23) + CC(CCOO)OO(183) <=> C4H9O4(181) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.46478,'cm^3/(mol*s)'), n=2.82028, Ea=(13.3554,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.68355, dn = +|- 0.0684363, dEa = +|- 0.372428 kJ/mol"""),
)

entry(
    index = 1103,
    label = "CO[O](30) + [CH2]C=O <=> COO + C2H2O(603)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(584.192,'cm^3/(mol*s)'), n=3.33428, Ea=(60.9947,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.27921, dn = +|- 0.0323517, dEa = +|- 0.176057 kJ/mol"""),
)

entry(
    index = 1658,
    label = "[CH2]C=O + CCO[O](28) <=> C2H2O(603) + CCOO(54)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.150922,'cm^3/(mol*s)'), n=4.25575, Ea=(60.5347,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.62947, dn = +|- 0.0641471, dEa = +|- 0.349086 kJ/mol"""),
)

entry(
    index = 1721,
    label = "[CH2]C=O + CCC(C)O[O](52) <=> C2H2O(603) + CCC(C)OO(80)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.75331e-06,'cm^3/(mol*s)'), n=5.59479, Ea=(58.4436,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 2.27322, dn = +|- 0.107889, dEa = +|- 0.587128 kJ/mol"""),
)

entry(
    index = 2291,
    label = "[CH2]C=O + [CH2]C=O <=> C2H2O(603) + C=CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8.57019,'cm^3/(mol*s)'), n=3.63412, Ea=(74.6787,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.51481, dn = +|- 0.0545607, dEa = +|- 0.296917 kJ/mol"""),
)

entry(
    index = 2303,
    label = "[CH2]C=O + C[CH2](20) <=> C2H4(11) + C=CO",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.00470873,'cm^3/(mol*s)'), n=4.57139, Ea=(106.899,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11607, dn = +|- 0.0144275, dEa = +|- 0.0785141 kJ/mol"""),
)

entry(
    index = 2313,
    label = "[CH2]C=O + [CH2]CCC(24) <=> C=CO + C4H8(47)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0131001,'cm^3/(mol*s)'), n=4.3436, Ea=(98.9958,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.82561, dn = +|- 0.0790797, dEa = +|- 0.430349 kJ/mol"""),
)

entry(
    index = 4721,
    label = "HO2(16) + C[CH]CC(23) <=> O2(2) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.30975,'cm^3/(mol*s)'), n=3.39011, Ea=(-18.8618,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.23623, dn = +|- 0.0278614, dEa = +|- 0.15162 kJ/mol"""),
)

entry(
    index = 4724,
    label = "H2O2(17) + C[CH]CC(23) <=> HO2(16) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.311949,'cm^3/(mol*s)'), n=3.67012, Ea=(20.9134,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.23306, dn = +|- 0.0275238, dEa = +|- 0.149783 kJ/mol"""),
)

entry(
    index = 4728,
    label = "CCOO(54) + C[CH]CC(23) <=> CCO[O](28) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.089556,'cm^3/(mol*s)'), n=3.61357, Ea=(17.7093,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.07652, dn = +|- 0.00968715, dEa = +|- 0.0527171 kJ/mol"""),
)

entry(
    index = 4729,
    label = "C[CH]CC(23) + CCC(C)OO(80) <=> CCC(C)O[O](52) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.54688e-08,'cm^3/(mol*s)'), n=5.09842, Ea=(16.7998,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.20371, dn = +|- 0.0243594, dEa = +|- 0.132563 kJ/mol"""),
)

entry(
    index = 4736,
    label = "H2O2(17) + [CH2]CCC(24) <=> HO2(16) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.21137e-05,'cm^3/(mol*s)'), n=4.6295, Ea=(17.3282,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.16, dn = +|- 0.0194991, dEa = +|- 0.106113 kJ/mol"""),
)

entry(
    index = 4737,
    label = "CCOO(54) + [CH2]CCC(24) <=> CCO[O](28) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8.79774e-07,'cm^3/(mol*s)'), n=5.27271, Ea=(15.9338,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 2.26517, dn = +|- 0.107423, dEa = +|- 0.584592 kJ/mol"""),
)

entry(
    index = 4738,
    label = "[CH2]CCC(24) + CCC(C)OO(80) <=> CCC(C)O[O](52) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.0300326,'cm^3/(mol*s)'), n=3.71314, Ea=(18.7068,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.26457, dn = +|- 0.0308387, dEa = +|- 0.167823 kJ/mol"""),
)

entry(
    index = 4741,
    label = "C2H4(11) + C[CH2](20) <=> [CH2]CCC(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(7356.58,'cm^3/(mol*s)'), n=2.62378, Ea=(26.6181,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01268, dn = +|- 0.00165589, dEa = +|- 0.00901131 kJ/mol"""),
)

entry(
    index = 4744,
    label = "C[CH]CCOO(223) <=> CCCCO[O](215)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3.69053e+06,'s^-1'), n=0.898202, Ea=(31.3526,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.52959, dn = +|- 0.0558369, dEa = +|- 0.303862 kJ/mol"""),
)

entry(
    index = 4752,
    label = "C4H9O4(181) <=> OH + C4H8O3",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.50689e+10,'s^-1'), n=0.438901, Ea=(104.55,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.19528, dn = +|- 0.0234354, dEa = +|- 0.127534 kJ/mol"""),
)

entry(
    index = 4778,
    label = "C[CH]CC(23) + CCCCOO(226) <=> CCCCO[O](215) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.79477e-05,'cm^3/(mol*s)'), n=4.74292, Ea=(19.0847,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.21205, dn = +|- 0.0252658, dEa = +|- 0.137496 kJ/mol"""),
)

entry(
    index = 4779,
    label = "[CH2]CCC(24) + CCCCOO(226) <=> CCCCO[O](215) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.33231e-12,'cm^3/(mol*s)'), n=6.55517, Ea=(6.18281,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.34826, dn = +|- 0.0392587, dEa = +|- 0.213644 kJ/mol"""),
)

entry(
    index = 4836,
    label = "O2(2) + O[CH]CCCOO(1028) <=> HO2(16) + C4H8O3(1060)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.90514e+09,'cm^3/(mol*s)'), n=1.45799, Ea=(241.359,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.13581, dn = +|- 0.016731, dEa = +|- 0.0910493 kJ/mol"""),
)

entry(
    index = 4890,
    label = "[CH2]C=O + CCCCO[O](215) <=> C2H2O(603) + CCCCOO(226)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(7.03889e-07,'cm^3/(mol*s)'), n=5.37947, Ea=(54.0258,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.61449, dn = +|- 0.0629333, dEa = +|- 0.342481 kJ/mol"""),
)

entry(
    index = 5046,
    label = "COO + C[CH]CC(23) <=> CO[O](30) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.319617,'cm^3/(mol*s)'), n=3.63193, Ea=(22.9953,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.48035, dn = +|- 0.0515372, dEa = +|- 0.280463 kJ/mol"""),
)

entry(
    index = 5047,
    label = "COO + [CH2]CCC(24) <=> CO[O](30) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.76139e-05,'cm^3/(mol*s)'), n=4.93459, Ea=(18.0377,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.91579, dn = +|- 0.0854144, dEa = +|- 0.464822 kJ/mol"""),
)

entry(
    index = 5226,
    label = "CCCOO + C[CH]CC(23) <=> CCCO[O](63) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.000261799,'cm^3/(mol*s)'), n=3.58241, Ea=(6.81089,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.64574, dn = +|- 0.0654525, dEa = +|- 0.35619 kJ/mol"""),
)

entry(
    index = 5401,
    label = "C[CH]CC(23) + OOCCCCOO <=> [O]OCCCCOO(961) + butane(1)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.49987e-07,'cm^3/(mol*s)'), n=4.67052, Ea=(19.7244,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.25139, dn = +|- 0.0294625, dEa = +|- 0.160334 kJ/mol"""),
)

entry(
    index = 5446,
    label = "O2(2) + [O]CCCCOO <=> HO2(16) + C4H8O3(1060)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.05046e+08,'cm^3/(mol*s)'), n=1.7942, Ea=(297.486,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.20452, dn = +|- 0.0244476, dEa = +|- 0.133043 kJ/mol"""),
)

entry(
    index = 7841,
    label = "O2(2) + C4H7O2(1074) <=> HO2(16) + O=CCCC=O",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.25562,'cm^3/(mol*s)'), n=3.97963, Ea=(159.967,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.37713, dn = +|- 0.0420417, dEa = +|- 0.228789 kJ/mol"""),
)

entry(
    index = 30866,
    label = "[CH2]C=O + [CH2]C=C <=> C=CO + C=C=C",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(224715,'cm^3/(mol*s)'), n=2.41115, Ea=(-5.05085,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.22977, dn = +|- 0.0271734, dEa = +|- 0.147877 kJ/mol"""),
)

