#!/usr/bin/env python
# encoding: utf-8

name = "PCI2017/052-Stagni"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2017/052-Stagni
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + CH2CHO => CH2CO + HO2""",
)

entry(
    index = 1,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+11,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + NC4H9P => NC4H8 + HO2""",
)

entry(
    index = 2,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'s^-1'), n=0, Ea=(20500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is NC4H9-OO <=> NC4-QOOH""",
)

