# Generated by Django 4.2.24 on 2026-01-30 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("database", "0002_add_author_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apparatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shock tube", "Shock Tube"),
                            ("rapid compression machine", "Rapid Compression Machine"),
                        ],
                        help_text="Type of apparatus",
                        max_length=50,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=255)),
                (
                    "facility",
                    models.CharField(
                        blank=True,
                        help_text="Specific facility name (e.g., 'low pressure shock tube')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apparatus",
                "db_table": "chemked_apparatus",
                "unique_together": {("kind", "institution", "facility")},
            },
        ),
        migrations.CreateModel(
            name="ExperimentDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="Temperature in Kelvin",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("temperature_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "temperature_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        help_text="Pressure in Pascals",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("pressure_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "pressure_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "ignition_delay",
                    models.FloatField(
                        blank=True,
                        help_text="Ignition delay in seconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ignition_delay_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "ignition_delay_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "first_stage_ignition_delay",
                    models.FloatField(
                        blank=True, help_text="First stage ignition delay in seconds", null=True
                    ),
                ),
                (
                    "ignition_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("temperature", "Temperature"),
                            ("pressure", "Pressure"),
                            ("OH", "OH"),
                            ("OH*", "OH*"),
                            ("CH", "CH"),
                            ("CH*", "CH*"),
                        ],
                        help_text="Overrides dataset common_ignition_target if set",
                        max_length=20,
                    ),
                ),
                (
                    "ignition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("d/dt max", "d/dt max"),
                            ("max", "max"),
                            ("1/2 max", "1/2 max"),
                            ("min", "min"),
                            ("d/dt max extrapolated", "d/dt max extrapolated"),
                        ],
                        help_text="Overrides dataset common_ignition_type if set",
                        max_length=30,
                    ),
                ),
                (
                    "equivalence_ratio",
                    models.FloatField(
                        blank=True,
                        help_text="Fuel-air equivalence ratio (phi)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pressure_rise",
                    models.FloatField(blank=True, help_text="Pressure rise rate in 1/s", null=True),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        help_text="Composition data - null means use dataset common_composition",
                        null=True,
                    ),
                ),
                (
                    "composition_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mole fraction", "Mole Fraction"),
                            ("mass fraction", "Mass Fraction"),
                            ("mole percent", "Mole Percent"),
                        ],
                        help_text="Overrides dataset common composition kind if set",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "chemked_datapoints",
                "ordering": ["dataset", "temperature"],
            },
        ),
        migrations.CreateModel(
            name="VolumeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time_units", models.CharField(default="s", max_length=20)),
                ("volume_units", models.CharField(max_length=20)),
                ("values", models.JSONField(help_text="Array of [time, volume] pairs")),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volume_history",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "db_table": "chemked_volume_histories",
            },
        ),
        migrations.CreateModel(
            name="TimeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("volume", "Volume"),
                            ("temperature", "Temperature"),
                            ("pressure", "Pressure"),
                            ("piston position", "Piston Position"),
                            ("light emission", "Light Emission"),
                            ("OH emission", "OH Emission"),
                            ("absorption", "Absorption"),
                        ],
                        help_text="Type of time history data",
                        max_length=30,
                    ),
                ),
                ("time_units", models.CharField(default="s", max_length=20)),
                ("quantity_units", models.CharField(max_length=20)),
                (
                    "values",
                    models.JSONField(
                        blank=True,
                        help_text="Array of [time, value] or [time, value, uncertainty] pairs",
                        null=True,
                    ),
                ),
                ("source_filename", models.CharField(blank=True, max_length=500)),
                (
                    "uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                ("uncertainty_value", models.FloatField(blank=True, null=True)),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_histories",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time History",
                "verbose_name_plural": "Time Histories",
                "db_table": "chemked_time_histories",
            },
        ),
        migrations.CreateModel(
            name="ReferenceAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ORCID identifier (if available)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "chemked_reference_authors",
                "unique_together": {("name", "orcid")},
            },
        ),
        migrations.CreateModel(
            name="RCMData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "compressed_temperature",
                    models.FloatField(
                        blank=True, help_text="Temperature at end of compression (K)", null=True
                    ),
                ),
                ("compressed_temperature_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "compressed_temperature_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "compressed_pressure",
                    models.FloatField(
                        blank=True, help_text="Pressure at end of compression (Pa)", null=True
                    ),
                ),
                ("compressed_pressure_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "compressed_pressure_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "compression_time",
                    models.FloatField(
                        blank=True, help_text="Duration of compression stroke (s)", null=True
                    ),
                ),
                (
                    "stroke",
                    models.FloatField(blank=True, help_text="Piston stroke length (m)", null=True),
                ),
                (
                    "clearance",
                    models.FloatField(
                        blank=True, help_text="Clearance at end of compression (m)", null=True
                    ),
                ),
                (
                    "compression_ratio",
                    models.FloatField(
                        blank=True, help_text="Volumetric compression ratio", null=True
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rcm_data",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "RCM Data",
                "verbose_name_plural": "RCM Data",
                "db_table": "chemked_rcm_data",
            },
        ),
        migrations.CreateModel(
            name="FileAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ORCID identifier (e.g., 0000-0003-4425-7097)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "chemked_file_authors",
                "unique_together": {("name", "orcid")},
            },
        ),
        migrations.CreateModel(
            name="ExperimentDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemked_file_path",
                    models.CharField(
                        help_text="Original file path in ChemKED-database",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("file_version", models.IntegerField(default=0)),
                ("chemked_version", models.CharField(default="0.4.1", max_length=20)),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[("ignition delay", "Ignition Delay")],
                        default="ignition delay",
                        max_length=50,
                    ),
                ),
                ("reference_doi", models.CharField(blank=True, db_index=True, max_length=255)),
                ("reference_journal", models.CharField(blank=True, max_length=255)),
                ("reference_year", models.IntegerField(blank=True, null=True)),
                ("reference_volume", models.IntegerField(blank=True, null=True)),
                ("reference_pages", models.CharField(blank=True, max_length=100)),
                ("reference_detail", models.TextField(blank=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "apparatus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to="chemked_database.apparatus",
                    ),
                ),
                (
                    "file_authors",
                    models.ManyToManyField(
                        blank=True, related_name="datasets", to="chemked_database.fileauthor"
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chemked_datasets",
                        to="database.source",
                    ),
                ),
                (
                    "reference_authors",
                    models.ManyToManyField(
                        blank=True, related_name="datasets", to="chemked_database.referenceauthor"
                    ),
                ),
            ],
            options={
                "db_table": "chemked_datasets",
                "ordering": ["reference_year", "chemked_file_path"],
            },
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datapoints",
                to="chemked_database.experimentdataset",
            ),
        ),
        migrations.CreateModel(
            name="CompositionSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("species_name", models.CharField(db_index=True, max_length=255)),
                (
                    "inchi",
                    models.CharField(
                        blank=True, db_index=True, help_text="InChI identifier", max_length=500
                    ),
                ),
                ("smiles", models.CharField(blank=True, max_length=500)),
                (
                    "atomic_composition",
                    models.JSONField(
                        blank=True,
                        help_text="Atomic composition list of {element, amount}",
                        null=True,
                    ),
                ),
                (
                    "thermo",
                    models.JSONField(
                        blank=True, help_text="Thermo data block (T_ranges, data, note)", null=True
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        help_text="Amount (units depend on composition kind)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("amount_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "amount_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                ("amount_upper_uncertainty", models.FloatField(blank=True, null=True)),
                ("amount_lower_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "database_species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chemked_occurrences",
                        to="database.species",
                    ),
                ),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composition_species",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "db_table": "chemked_composition_species",
                "ordering": ["-amount"],
            },
        ),
        migrations.CreateModel(
            name="CommonProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        help_text="Shared composition if same for all datapoints",
                        null=True,
                    ),
                ),
                (
                    "composition_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mole fraction", "Mole Fraction"),
                            ("mass fraction", "Mass Fraction"),
                            ("mole percent", "Mole Percent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ignition_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("temperature", "Temperature"),
                            ("pressure", "Pressure"),
                            ("OH", "OH"),
                            ("OH*", "OH*"),
                            ("CH", "CH"),
                            ("CH*", "CH*"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ignition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("d/dt max", "d/dt max"),
                            ("max", "max"),
                            ("1/2 max", "1/2 max"),
                            ("min", "min"),
                            ("d/dt max extrapolated", "d/dt max extrapolated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pressure",
                    models.FloatField(
                        blank=True,
                        help_text="Common pressure in Pa if same for all datapoints",
                        null=True,
                    ),
                ),
                ("pressure_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "pressure_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "pressure_rise",
                    models.FloatField(blank=True, help_text="Pressure rise rate in 1/s", null=True),
                ),
                ("pressure_rise_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "pressure_rise_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="common_properties",
                        to="chemked_database.experimentdataset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Common Properties",
                "db_table": "chemked_common_properties",
            },
        ),
        migrations.AddConstraint(
            model_name="compositionspecies",
            constraint=models.UniqueConstraint(
                fields=("datapoint", "species_name", "inchi", "smiles"),
                name="chemked_unique_species_per_datapoint",
            ),
        ),
    ]
