# Generated by Django 4.2.24 on 2026-01-30 02:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="first_stage_ignition_delay",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="ignition_delay",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="ignition_delay_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="ignition_delay_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="ignition_target",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="ignition_type",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="pressure_rise",
        ),
        migrations.AlterField(
            model_name="experimentdataset",
            name="experiment_type",
            field=models.CharField(
                choices=[
                    ("ignition delay", "Ignition Delay"),
                    ("laminar flame speed", "Laminar Flame Speed"),
                    ("species profile", "Species Profile"),
                ],
                default="ignition delay",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="SpeciesProfileDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("species_name", models.CharField(max_length=255)),
                ("inchi", models.CharField(blank=True, max_length=500)),
                ("smiles", models.CharField(blank=True, max_length=500)),
                ("time_units", models.CharField(default="s", max_length=20)),
                (
                    "quantity_units",
                    models.CharField(help_text="Species concentration units", max_length=50),
                ),
                (
                    "values",
                    models.JSONField(
                        help_text="Array of [time, value] or [time, value, uncertainty] pairs"
                    ),
                ),
                (
                    "uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                ("uncertainty_value", models.FloatField(blank=True, null=True)),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_profile",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Profile Datapoint",
                "verbose_name_plural": "Species Profile Datapoints",
                "db_table": "chemked_species_profile",
            },
        ),
        migrations.CreateModel(
            name="IgnitionDelayDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ignition_delay",
                    models.FloatField(
                        blank=True,
                        help_text="Ignition delay in seconds",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("ignition_delay_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "ignition_delay_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "first_stage_ignition_delay",
                    models.FloatField(
                        blank=True, help_text="First stage ignition delay in seconds", null=True
                    ),
                ),
                (
                    "ignition_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("temperature", "Temperature"),
                            ("pressure", "Pressure"),
                            ("OH", "OH"),
                            ("OH*", "OH*"),
                            ("CH", "CH"),
                            ("CH*", "CH*"),
                        ],
                        help_text="Overrides dataset common ignition target if set",
                        max_length=20,
                    ),
                ),
                (
                    "ignition_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("d/dt max", "d/dt max"),
                            ("max", "max"),
                            ("1/2 max", "1/2 max"),
                            ("min", "min"),
                            ("d/dt max extrapolated", "d/dt max extrapolated"),
                        ],
                        help_text="Overrides dataset common ignition type if set",
                        max_length=30,
                    ),
                ),
                (
                    "pressure_rise",
                    models.FloatField(blank=True, help_text="Pressure rise rate in 1/s", null=True),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignition_delay",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignition Delay Datapoint",
                "verbose_name_plural": "Ignition Delay Datapoints",
                "db_table": "chemked_ignition_delay",
            },
        ),
        migrations.CreateModel(
            name="FlameSpeedDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "laminar_flame_speed",
                    models.FloatField(
                        blank=True,
                        help_text="Laminar flame speed in m/s",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("laminar_flame_speed_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "laminar_flame_speed_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "stretch",
                    models.FloatField(blank=True, help_text="Flame stretch rate in 1/s", null=True),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flame_speed",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flame Speed Datapoint",
                "verbose_name_plural": "Flame Speed Datapoints",
                "db_table": "chemked_flame_speed",
            },
        ),
    ]
