# Generated by Django 4.2.24 on 2026-01-30 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0002_remove_experimentdatapoint_first_stage_ignition_delay_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueWithUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                (
                    "value_text",
                    models.CharField(
                        blank=True, help_text="Raw value string if provided as text", max_length=100
                    ),
                ),
                ("units", models.CharField(max_length=50)),
                (
                    "uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                ("uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "uncertainty_text",
                    models.CharField(
                        blank=True,
                        help_text="Raw uncertainty string if provided as text",
                        max_length=100,
                    ),
                ),
                ("upper_uncertainty", models.FloatField(blank=True, null=True)),
                ("lower_uncertainty", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "chemked_value_units",
            },
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="pressure_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_pressure_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="pressure_rise_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_pressure_rise_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="pressure_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pressure_datapoints",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="temperature_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="temperature_datapoints",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="flamespeeddatapoint",
            name="laminar_flame_speed_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flame_speeds",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="flamespeeddatapoint",
            name="stretch_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flame_stretch_rates",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="ignitiondelaydatapoint",
            name="first_stage_ignition_delay_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_stage_ignition_delays",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="ignitiondelaydatapoint",
            name="ignition_delay_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ignition_delays",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="ignitiondelaydatapoint",
            name="pressure_rise_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ignition_pressure_rises",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="clearance_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_clearance",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="compressed_pressure_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_compressed_pressure",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="compressed_temperature_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_compressed_temperature",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="compression_ratio_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_compression_ratio",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="compression_time_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_compression_time",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="rcmdata",
            name="stroke_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rcm_stroke",
                to="chemked_database.valuewithunit",
            ),
        ),
    ]
