# Generated by Django 4.2.24 on 2026-01-30 16:57

from django.db import migrations, models
import django.db.models.deletion


def _build_composition(composition_data, Composition, CompositionSpecies, SpeciesThermo, datapoint=None):
    if not composition_data:
        return None

    composition = Composition.objects.create(
        kind=composition_data.get("kind", ""),
    )

    for species in composition_data.get("species", []) or []:
        amount_list = species.get("amount") or []
        amount_value = None
        amount_uncertainty = None
        amount_uncertainty_type = ""
        amount_upper = None
        amount_lower = None

        if amount_list:
            try:
                amount_value = float(amount_list[0])
            except (TypeError, ValueError):
                amount_value = None
        if len(amount_list) > 1 and isinstance(amount_list[1], dict):
            amount_uncertainty_type = amount_list[1].get("uncertainty-type", "")
            amount_uncertainty = amount_list[1].get("uncertainty")
            amount_upper = amount_list[1].get("upper-uncertainty")
            amount_lower = amount_list[1].get("lower-uncertainty")

        composition_species = CompositionSpecies.objects.create(
            composition=composition,
            datapoint=datapoint,
            species_name=species.get("species-name", ""),
            inchi=species.get("InChI", ""),
            smiles=species.get("SMILES", ""),
            atomic_composition=species.get("atomic-composition"),
            amount=amount_value or 0.0,
            amount_uncertainty=amount_uncertainty,
            amount_uncertainty_type=amount_uncertainty_type,
            amount_upper_uncertainty=amount_upper,
            amount_lower_uncertainty=amount_lower,
        )

        thermo = species.get("thermo") or {}
        if thermo:
            t_ranges = thermo.get("T_ranges", [])
            data = thermo.get("data", [])
            SpeciesThermo.objects.create(
                species=composition_species,
                t_range_1=str(t_ranges[0]) if len(t_ranges) > 0 else "",
                t_range_2=str(t_ranges[1]) if len(t_ranges) > 1 else "",
                t_range_3=str(t_ranges[2]) if len(t_ranges) > 2 else "",
                coeff_1=data[0] if len(data) > 0 else None,
                coeff_2=data[1] if len(data) > 1 else None,
                coeff_3=data[2] if len(data) > 2 else None,
                coeff_4=data[3] if len(data) > 3 else None,
                coeff_5=data[4] if len(data) > 4 else None,
                coeff_6=data[5] if len(data) > 5 else None,
                coeff_7=data[6] if len(data) > 6 else None,
                coeff_8=data[7] if len(data) > 7 else None,
                coeff_9=data[8] if len(data) > 8 else None,
                coeff_10=data[9] if len(data) > 9 else None,
                coeff_11=data[10] if len(data) > 10 else None,
                coeff_12=data[11] if len(data) > 11 else None,
                coeff_13=data[12] if len(data) > 12 else None,
                coeff_14=data[13] if len(data) > 13 else None,
                note=thermo.get("note", ""),
            )

    return composition


def forwards(apps, schema_editor):
    Composition = apps.get_model("chemked_database", "Composition")
    CompositionSpecies = apps.get_model("chemked_database", "CompositionSpecies")
    SpeciesThermo = apps.get_model("chemked_database", "SpeciesThermo")
    ExperimentDatapoint = apps.get_model("chemked_database", "ExperimentDatapoint")
    CommonProperties = apps.get_model("chemked_database", "CommonProperties")

    for common_props in CommonProperties.objects.exclude(composition=None):
        comp = _build_composition(common_props.composition, Composition, CompositionSpecies, SpeciesThermo)
        common_props.composition_fk = comp
        common_props.save(update_fields=["composition_fk"])

    for datapoint in ExperimentDatapoint.objects.exclude(composition=None):
        comp = _build_composition(datapoint.composition, Composition, CompositionSpecies, SpeciesThermo, datapoint)
        datapoint.composition_fk = comp
        datapoint.save(update_fields=["composition_fk"])

        for species in CompositionSpecies.objects.filter(datapoint=datapoint):
            species.composition = comp
            species.save(update_fields=["composition"])

    for species in CompositionSpecies.objects.filter(composition__isnull=True):
        datapoint = getattr(species, "datapoint", None)
        if datapoint and datapoint.composition_fk:
            species.composition = datapoint.composition_fk
            species.save(update_fields=["composition"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("chemked_database", "0003_valuewithunit_commonproperties_pressure_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mole fraction", "Mole Fraction"),
                            ("mass fraction", "Mass Fraction"),
                            ("mole percent", "Mole Percent"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "chemked_compositions",
            },
        ),
        migrations.CreateModel(
            name="SpeciesThermo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("t_range_1", models.CharField(max_length=50)),
                ("t_range_2", models.CharField(max_length=50)),
                ("t_range_3", models.CharField(max_length=50)),
                ("coeff_1", models.FloatField(blank=True, null=True)),
                ("coeff_2", models.FloatField(blank=True, null=True)),
                ("coeff_3", models.FloatField(blank=True, null=True)),
                ("coeff_4", models.FloatField(blank=True, null=True)),
                ("coeff_5", models.FloatField(blank=True, null=True)),
                ("coeff_6", models.FloatField(blank=True, null=True)),
                ("coeff_7", models.FloatField(blank=True, null=True)),
                ("coeff_8", models.FloatField(blank=True, null=True)),
                ("coeff_9", models.FloatField(blank=True, null=True)),
                ("coeff_10", models.FloatField(blank=True, null=True)),
                ("coeff_11", models.FloatField(blank=True, null=True)),
                ("coeff_12", models.FloatField(blank=True, null=True)),
                ("coeff_13", models.FloatField(blank=True, null=True)),
                ("coeff_14", models.FloatField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Species Thermo",
                "verbose_name_plural": "Species Thermo",
                "db_table": "chemked_species_thermo",
            },
        ),
        migrations.RemoveConstraint(
            model_name="compositionspecies",
            name="chemked_unique_species_per_datapoint",
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="composition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="species",
                to="chemked_database.composition",
            ),
        ),
        migrations.AddField(
            model_name="speciesthermo",
            name="species",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thermo_data",
                to="chemked_database.compositionspecies",
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="composition_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datapoints_temp",
                to="chemked_database.composition",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="composition_fk",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_properties_temp",
                to="chemked_database.composition",
            ),
        ),
        migrations.AlterField(
            model_name="compositionspecies",
            name="datapoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="composition_species",
                to="chemked_database.experimentdatapoint",
            ),
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="composition_kind",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="composition_kind",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="composition",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="composition",
        ),
        migrations.RemoveField(
            model_name="compositionspecies",
            name="datapoint",
        ),
        migrations.RemoveField(
            model_name="compositionspecies",
            name="thermo",
        ),
        migrations.RenameField(
            model_name="experimentdatapoint",
            old_name="composition_fk",
            new_name="composition",
        ),
        migrations.RenameField(
            model_name="commonproperties",
            old_name="composition_fk",
            new_name="composition",
        ),
        migrations.AddConstraint(
            model_name="compositionspecies",
            constraint=models.UniqueConstraint(
                fields=("composition", "species_name", "inchi", "smiles"),
                name="chemked_unique_species_per_datapoint",
            ),
        ),
    ]
