# Generated by Django 4.2.24 on 2026-01-30 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0004_composition_speciesthermo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonproperties",
            name="composition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_properties",
                to="chemked_database.composition",
            ),
        ),
        migrations.AlterField(
            model_name="experimentdatapoint",
            name="composition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datapoints",
                to="chemked_database.composition",
            ),
        ),
    ]
