# Generated by Django 4.2.24 on 2026-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0005_alter_commonproperties_composition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="kind",
            field=models.CharField(
                choices=[
                    ("mole fraction", "Mole Fraction"),
                    ("mass fraction", "Mass Fraction"),
                    ("mole percent", "Mole Percent"),
                ],
                max_length=20,
            ),
        ),
    ]
