# Generated by Django 4.2.24 on 2026-02-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0006_alter_composition_kind_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdataset",
            name="experiment_type",
            field=models.CharField(
                choices=[
                    ("ignition delay", "Ignition Delay"),
                    ("laminar flame speed", "Laminar Flame Speed"),
                    ("species profile", "Species Profile"),
                    ("rate coefficient", "Rate Coefficient"),
                    ("thermochemical", "Thermochemical"),
                ],
                default="ignition delay",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RateCoefficientDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rate_coefficient",
                    models.FloatField(blank=True, help_text="Rate coefficient value", null=True),
                ),
                (
                    "rate_coefficient_units",
                    models.CharField(
                        blank=True,
                        default="cm3 mol-1 s-1",
                        help_text="Units for rate coefficient (e.g., cm3 mol-1 s-1)",
                        max_length=50,
                    ),
                ),
                ("rate_coefficient_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "rate_coefficient_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "reaction",
                    models.CharField(
                        blank=True,
                        help_text="Reaction equation (e.g., NO2 + HO2 = HNO2 + O2)",
                        max_length=500,
                    ),
                ),
                (
                    "reaction_order",
                    models.IntegerField(blank=True, help_text="Overall reaction order", null=True),
                ),
                (
                    "bulk_gas",
                    models.CharField(
                        blank=True, help_text="Bulk gas (e.g., N2, Ar)", max_length=50
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="Experimental or computational method (e.g., ab initio CBS-QB3)",
                        max_length=255,
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_coefficient",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Coefficient Datapoint",
                "verbose_name_plural": "Rate Coefficient Datapoints",
                "db_table": "chemked_rate_coefficient",
            },
        ),
    ]
