# Generated by Django 4.2.24 on 2026-02-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0008_add_jsr_experiment_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesConcentration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "species_name",
                    models.CharField(
                        help_text="Species name/key (e.g., CH3OH, CO, CO2)", max_length=100
                    ),
                ),
                (
                    "cas",
                    models.CharField(blank=True, help_text="CAS registry number", max_length=20),
                ),
                ("inchi", models.CharField(blank=True, help_text="InChI string", max_length=500)),
                ("smiles", models.CharField(blank=True, help_text="SMILES string", max_length=500)),
                ("concentration", models.FloatField(help_text="Concentration value")),
                (
                    "concentration_units",
                    models.CharField(
                        default="mole fraction",
                        help_text="Units (e.g., mole fraction, ppm)",
                        max_length=50,
                    ),
                ),
                ("concentration_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "concentration_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "datapoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_concentrations",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Concentration",
                "verbose_name_plural": "Species Concentrations",
                "db_table": "chemked_species_concentration",
            },
        ),
        migrations.CreateModel(
            name="JSRDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "residence_time",
                    models.FloatField(blank=True, help_text="Residence time in seconds", null=True),
                ),
                ("residence_time_units", models.CharField(blank=True, default="s", max_length=20)),
                ("residence_time_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "residence_time_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "reactor_volume",
                    models.FloatField(blank=True, help_text="Reactor volume in m³", null=True),
                ),
                ("reactor_volume_units", models.CharField(blank=True, default="m3", max_length=20)),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jsr_data",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "JSR Datapoint",
                "verbose_name_plural": "JSR Datapoints",
                "db_table": "chemked_jsr_datapoint",
            },
        ),
    ]
