# Generated by Django 4.2.24 on 2026-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0009_add_jsr_and_species_concentration"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositionspecies",
            name="cas",
            field=models.CharField(
                blank=True, db_index=True, help_text="CAS Registry Number", max_length=50
            ),
        ),
    ]
