# Generated by Django 4.2.24 on 2026-02-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0010_add_cas_to_composition_species"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speciesconcentration",
            name="datapoint",
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="equivalence_ratio",
            field=models.FloatField(
                blank=True, help_text="Fuel-air equivalence ratio (phi)", null=True
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="reactor_volume",
            field=models.FloatField(blank=True, help_text="Reactor volume in m³", null=True),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="reactor_volume_units",
            field=models.CharField(blank=True, default="m3", max_length=20),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="residence_time",
            field=models.FloatField(blank=True, help_text="Residence time in seconds", null=True),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="residence_time_units",
            field=models.CharField(blank=True, default="s", max_length=20),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="chem_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable chemical name (e.g., 'methanol')",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="position",
            field=models.FloatField(
                blank=True,
                help_text="Spatial position (distance from burner, position along reactor) in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="position_units",
            field=models.CharField(
                blank=True,
                default="m",
                help_text="Original units for position (mm, cm, m)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="comments",
            field=models.JSONField(
                blank=True, default=list, help_text="List of comments from the data file"
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="file_doi",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="File DOI (e.g., 10.24388/x00002001)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="first_publication_date",
            field=models.DateField(
                blank=True, help_text="First publication date of the data file", null=True
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="last_modification_date",
            field=models.DateField(
                blank=True, help_text="Last modification date of the data file", null=True
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="method",
            field=models.TextField(
                blank=True, help_text="Experimental or computational method description"
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="reference_figure",
            field=models.CharField(
                blank=True, help_text="Figure reference (e.g., 'Fig. 2')", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="reference_location",
            field=models.CharField(
                blank=True, help_text="Location in reference (e.g., 'Main article')", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="reference_table",
            field=models.CharField(
                blank=True, help_text="Table reference (e.g., 'Table I')", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="reference_title",
            field=models.TextField(blank=True, help_text="Full title of the reference paper"),
        ),
        migrations.AddField(
            model_name="experimentdataset",
            name="respecth_version",
            field=models.CharField(
                blank=True, help_text="ReSpecTh schema version (e.g., 2.3)", max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="JSRDatapoint",
        ),
        migrations.DeleteModel(
            name="SpeciesConcentration",
        ),
    ]
