# Generated by Django 4.2.24 on 2026-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0011_add_respecth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="experimentdatapoint",
            name="residence_time",
            field=models.FloatField(
                blank=True,
                help_text="Residence time in seconds (for time-series experiments)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="residence_time_units",
            field=models.CharField(
                blank=True,
                default="s",
                help_text="Original units for residence time",
                max_length=20,
            ),
        ),
    ]
