# Generated by Django 4.2.24 on 2026-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0012_add_datapoint_residence_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdataset",
            name="experiment_type",
            field=models.CharField(
                choices=[
                    ("ignition delay", "Ignition Delay"),
                    ("laminar flame speed", "Laminar Flame Speed"),
                    ("species profile", "Species Profile"),
                    ("rate coefficient", "Rate Coefficient"),
                    ("thermochemical", "Thermochemical"),
                    ("jet stirred reactor measurement", "Jet Stirred Reactor Measurement"),
                    ("concentration profile", "Concentration Profile"),
                    ("outlet concentration measurement", "Outlet Concentration Measurement"),
                ],
                default="ignition delay",
                max_length=50,
            ),
        ),
    ]
