# Generated by Django 4.2.24 on 2026-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0013_add_outlet_concentration_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentdataset",
            name="file_doi",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="File DOI (e.g., 10.24388/x00002001)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="experimentdataset",
            name="reference_figure",
            field=models.CharField(
                blank=True, help_text="Figure reference (e.g., 'Fig. 2')", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="experimentdataset",
            name="reference_table",
            field=models.CharField(
                blank=True, help_text="Table reference (e.g., 'Table I')", max_length=255
            ),
        ),
    ]
