# Generated by Django 4.2.29 on 2026-03-27 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0015_alter_experimentdataset_experiment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BurnerStabilizedFlameSpeciationMeasurementDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance from burner in meters", null=True
                    ),
                ),
                (
                    "flow_rate",
                    models.FloatField(
                        blank=True, help_text="Mass flow rate in kg m⁻² s⁻¹", null=True
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burner_stabilized_flame_speciation_measurement",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Burner Stabilized Flame Speciation Measurement Datapoint",
                "verbose_name_plural": "Burner Stabilized Flame Speciation Measurement Datapoints",
                "db_table": "chemked_burner_stabilized_flame_speciation_measurement",
            },
        ),
        migrations.CreateModel(
            name="ConcentrationTimeProfileMeasurementDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time_units", models.CharField(default="s", max_length=20)),
                (
                    "quantity_units",
                    models.CharField(
                        help_text="Species concentration units (e.g., mole fraction, ppm)",
                        max_length=50,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        help_text="Array of [time, value] or [time, value, uncertainty] pairs"
                    ),
                ),
                (
                    "uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                ("uncertainty_value", models.FloatField(blank=True, null=True)),
                (
                    "timeshift_target",
                    models.CharField(
                        blank=True,
                        help_text="Species name used as time shift reference",
                        max_length=255,
                    ),
                ),
                (
                    "timeshift_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("half decrease", "Half Decrease"),
                            ("relative decrease", "Relative Decrease"),
                        ],
                        help_text="Method for determining time shift",
                        max_length=30,
                    ),
                ),
                (
                    "timeshift_amount",
                    models.FloatField(
                        blank=True, help_text="Time shift amount in time_units", null=True
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_time_profile_measurement",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
                (
                    "tracked_species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Species being tracked over time",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="concentration_time_profiles",
                        to="chemked_database.compositionspecies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concentration Time Profile Measurement Datapoint",
                "verbose_name_plural": "Concentration Time Profile Measurement Datapoints",
                "db_table": "chemked_concentration_time_profile_measurement",
            },
        ),
        migrations.CreateModel(
            name="EvaluatedStandardDeviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Property this applies to (e.g., 'ignition delay', 'composition', 'laminar burning velocity')",
                        max_length=100,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        help_text="Absolute or relative",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("generic uncertainty", "Generic Uncertainty"),
                            (
                                "combined from scatter and reported uncertainty",
                                "Combined from Scatter and Reported Uncertainty",
                            ),
                            ("statistical scatter", "Statistical Scatter"),
                        ],
                        help_text="Method used to evaluate",
                        max_length=100,
                    ),
                ),
                ("value", models.FloatField(help_text="Standard deviation value")),
                (
                    "units",
                    models.CharField(
                        help_text="Units of the standard deviation value", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluated Standard Deviation",
                "verbose_name_plural": "Evaluated Standard Deviations",
                "db_table": "chemked_evaluated_std_deviation",
            },
        ),
        migrations.CreateModel(
            name="JetStirredReactorMeasurementDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jet_stirred_reactor_measurement",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
                (
                    "measured_composition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Measured species compositions at this T/P condition",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jsr_measurement_datapoints",
                        to="chemked_database.composition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jet Stirred Reactor Measurement Datapoint",
                "verbose_name_plural": "Jet Stirred Reactor Measurement Datapoints",
                "db_table": "chemked_jet_stirred_reactor_measurement",
            },
        ),
        migrations.CreateModel(
            name="LaminarBurningVelocityMeasurementDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "laminar_burning_velocity",
                    models.FloatField(
                        blank=True,
                        help_text="Laminar burning velocity in m/s",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("laminar_burning_velocity_uncertainty", models.FloatField(blank=True, null=True)),
                (
                    "laminar_burning_velocity_uncertainty_type",
                    models.CharField(
                        blank=True,
                        choices=[("absolute", "Absolute"), ("relative", "Relative")],
                        max_length=20,
                    ),
                ),
                (
                    "laminar_burning_velocity_uncertainty_bound",
                    models.CharField(
                        blank=True,
                        choices=[("plus", "Plus"), ("minus", "Minus"), ("plusminus", "Plus/Minus")],
                        max_length=20,
                    ),
                ),
                (
                    "stretch",
                    models.FloatField(blank=True, help_text="Flame stretch rate in 1/s", null=True),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laminar_burning_velocity_measurement",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laminar Burning Velocity Measurement Datapoint",
                "verbose_name_plural": "Laminar Burning Velocity Measurement Datapoints",
                "db_table": "chemked_laminar_burning_velocity_measurement",
            },
        ),
        migrations.CreateModel(
            name="OutletConcentrationMeasurementDatapoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "residence_time",
                    models.FloatField(
                        blank=True,
                        help_text="Residence time in seconds (per-datapoint override)",
                        null=True,
                    ),
                ),
                (
                    "volumetric_flow_in_reference_state",
                    models.FloatField(
                        blank=True,
                        help_text="Volumetric flow rate at reference conditions (m³/s)",
                        null=True,
                    ),
                ),
                (
                    "datapoint",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_concentration_measurement",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
                (
                    "initial_composition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Initial composition if different from common properties",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocm_initial_compositions",
                        to="chemked_database.composition",
                    ),
                ),
                (
                    "measured_composition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Measured species compositions at outlet",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocm_datapoints",
                        to="chemked_database.composition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outlet Concentration Measurement Datapoint",
                "verbose_name_plural": "Outlet Concentration Measurement Datapoints",
                "db_table": "chemked_outlet_concentration_measurement",
            },
        ),
        migrations.RemoveField(
            model_name="speciesprofiledatapoint",
            name="datapoint",
        ),
        migrations.AddField(
            model_name="apparatus",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reflected shock", "Reflected Shock"),
                    ("incident shock", "Incident Shock"),
                    ("laminar", "Laminar"),
                    ("burner stabilized", "Burner Stabilized"),
                    ("constant volume combustion chamber", "Constant Volume Combustion Chamber"),
                    ("premixed", "Premixed"),
                    ("unstretched", "Unstretched"),
                    (
                        "extrapolation method to zero stretch : LS",
                        "Extrapolation to Zero Stretch (LS)",
                    ),
                    (
                        "extrapolation method to zero stretch : NQ",
                        "Extrapolation to Zero Stretch (NQ)",
                    ),
                    ("counterflow", "Counterflow"),
                    ("OPF", "OPF"),
                    ("HFM", "HFM"),
                    ("CTF", "CTF"),
                    ("SFF", "SFF"),
                ],
                help_text="Operating mode (e.g., 'reflected shock', 'premixed')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="flow_rate",
            field=models.FloatField(
                blank=True, help_text="Mass flow rate in kg m⁻² s⁻¹", null=True
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="flow_rate_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_flow_rate_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="temperature",
            field=models.FloatField(
                blank=True,
                help_text="Common temperature in Kelvin if same for all datapoints",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="temperature_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_temperature_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="sourcetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reported", "Reported"),
                    ("estimated", "Estimated"),
                    ("calculated", "Calculated"),
                    ("digitized", "Digitized"),
                ],
                help_text="How this value was obtained (reported, estimated, calculated, digitized)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="uncertainty_bound",
            field=models.CharField(
                blank=True,
                choices=[("plus", "Plus"), ("minus", "Minus"), ("plusminus", "Plus/Minus")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apparatus",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shock tube", "Shock Tube"),
                    ("rapid compression machine", "Rapid Compression Machine"),
                    ("stirred reactor", "Stirred Reactor"),
                    ("stirred reactor (quartz)", "Stirred Reactor (Quartz)"),
                    ("stirred reactor (fused silica)", "Stirred Reactor (Fused Silica)"),
                    ("stirred reaction", "Stirred Reaction"),
                    ("jet stirred reactor", "Jet Stirred Reactor"),
                    ("flow reactor", "Flow Reactor"),
                    ("flow reactor (quartz)", "Flow Reactor (Quartz)"),
                    ("flow reactor (alumina)", "Flow Reactor (Alumina)"),
                    (
                        "flow reactor (recrystallized alumina)",
                        "Flow Reactor (Recrystallized Alumina)",
                    ),
                    ("flame", "Flame"),
                    (
                        "outwardly propagating spherical flame",
                        "Outwardly Propagating Spherical Flame",
                    ),
                    ("heat flux burner", "Heat Flux Burner"),
                ],
                help_text="Type of apparatus",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="commonproperties",
            name="ignition_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temperature", "Temperature"),
                    ("pressure", "Pressure"),
                    ("OH", "OH"),
                    ("OH*", "OH*"),
                    ("CH", "CH"),
                    ("CH*", "CH*"),
                    ("NH3", "NH3"),
                    ("CHEX", "CHEX"),
                    ("OHEX", "OHEX"),
                    ("p;", "P"),
                    ("CO2", "CO2"),
                    ("T", "T"),
                    ("N2O", "N2O"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="commonproperties",
            name="ignition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d/dt max", "d/dt max"),
                    ("max", "max"),
                    ("1/2 max", "1/2 max"),
                    ("min", "min"),
                    ("d/dt max extrapolated", "d/dt max extrapolated"),
                    ("relative concentration", "Relative Concentration"),
                    ("baseline min intercept from d/dt", "Baseline Min Intercept from d/dt"),
                    ("relative increase", "Relative Increase"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="experimentdataset",
            name="experiment_type",
            field=models.CharField(
                choices=[
                    ("ignition delay measurement", "Ignition Delay Measurement"),
                    (
                        "laminar burning velocity measurement",
                        "Laminar Burning Velocity Measurement",
                    ),
                    ("jet stirred reactor measurement", "Jet Stirred Reactor Measurement"),
                    ("outlet concentration measurement", "Outlet Concentration Measurement"),
                    (
                        "concentration time profile measurement",
                        "Concentration Time Profile Measurement",
                    ),
                    (
                        "burner stabilized flame speciation measurement",
                        "Burner Stabilized Flame Speciation Measurement",
                    ),
                    ("rate coefficient", "Rate Coefficient"),
                    ("thermochemical", "Thermochemical"),
                ],
                default="ignition delay measurement",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ignitiondelaydatapoint",
            name="ignition_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temperature", "Temperature"),
                    ("pressure", "Pressure"),
                    ("OH", "OH"),
                    ("OH*", "OH*"),
                    ("CH", "CH"),
                    ("CH*", "CH*"),
                    ("NH3", "NH3"),
                    ("CHEX", "CHEX"),
                    ("OHEX", "OHEX"),
                    ("p;", "P"),
                    ("CO2", "CO2"),
                    ("T", "T"),
                    ("N2O", "N2O"),
                ],
                help_text="Overrides dataset common ignition target if set",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ignitiondelaydatapoint",
            name="ignition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d/dt max", "d/dt max"),
                    ("max", "max"),
                    ("1/2 max", "1/2 max"),
                    ("min", "min"),
                    ("d/dt max extrapolated", "d/dt max extrapolated"),
                    ("relative concentration", "Relative Concentration"),
                    ("baseline min intercept from d/dt", "Baseline Min Intercept from d/dt"),
                    ("relative increase", "Relative Increase"),
                ],
                help_text="Overrides dataset common ignition type if set",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="FlameSpeedDatapoint",
        ),
        migrations.DeleteModel(
            name="SpeciesProfileDatapoint",
        ),
        migrations.AddField(
            model_name="outletconcentrationmeasurementdatapoint",
            name="residence_time_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocm_residence_times",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="outletconcentrationmeasurementdatapoint",
            name="volumetric_flow_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ocm_volumetric_flows",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="laminar_burning_velocity_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="laminar_burning_velocities",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="stretch_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flame_stretch_rates",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="evaluatedstandarddeviation",
            name="dataset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluated_std_deviations",
                to="chemked_database.experimentdataset",
            ),
        ),
        migrations.AddField(
            model_name="evaluatedstandarddeviation",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="For species-specific standard deviation (e.g., per-species in BSFSM)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluated_std_deviations",
                to="chemked_database.compositionspecies",
            ),
        ),
        migrations.AddField(
            model_name="burnerstabilizedflamespeciationmeasurementdatapoint",
            name="distance_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bsfsm_distances",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="burnerstabilizedflamespeciationmeasurementdatapoint",
            name="flow_rate_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bsfsm_flow_rates",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="burnerstabilizedflamespeciationmeasurementdatapoint",
            name="measured_composition",
            field=models.ForeignKey(
                blank=True,
                help_text="Measured species compositions at this distance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bsfsm_datapoints",
                to="chemked_database.composition",
            ),
        ),
    ]
