# Generated by Django 4.2.29 on 2026-03-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0016_burnerstabilizedflamespeciationmeasurementdatapoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonproperties",
            name="environment_temperature_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_environment_temperature_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="equivalence_ratio_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_equivalence_ratio_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="exchange_area_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_exchange_area_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="global_heat_exchange_coefficient_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_heat_exchange_coeff_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="laminar_burning_velocity_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_laminar_burning_velocity_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="pressure_in_reference_state_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_pressure_ref_state_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="reactor_diameter_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_reactor_diameter_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="reactor_length_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_reactor_length_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="reactor_volume_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_reactor_volume_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="residence_time_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_residence_time_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="commonproperties",
            name="temperature_in_reference_state_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="common_temperature_ref_state_sets",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="amount_evaluated_standard_deviation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="amount_evaluated_standard_deviation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generic uncertainty", "Generic Uncertainty"),
                    (
                        "combined from scatter and reported uncertainty",
                        "Combined from Scatter and Reported Uncertainty",
                    ),
                    ("statistical scatter", "Statistical Scatter"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="amount_evaluated_standard_deviation_sourcetype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="amount_evaluated_standard_deviation_type",
            field=models.CharField(
                blank=True,
                choices=[("absolute", "Absolute"), ("relative", "Relative")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="compositionspecies",
            name="amount_uncertainty_sourcetype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="concentrationtimeprofilemeasurementdatapoint",
            name="timeshift_amount_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ctpm_timeshift_amounts",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="evaluatedstandarddeviation",
            name="sourcetype",
            field=models.CharField(
                blank=True, help_text="How the standard deviation was obtained", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="experimentdatapoint",
            name="equivalence_ratio_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equivalence_ratio_datapoints",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="jetstirredreactormeasurementdatapoint",
            name="environment_temperature",
            field=models.FloatField(
                blank=True, help_text="Environment temperature in Kelvin", null=True
            ),
        ),
        migrations.AddField(
            model_name="jetstirredreactormeasurementdatapoint",
            name="environment_temperature_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jsr_environment_temperatures",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="pressure_rise",
            field=models.FloatField(blank=True, help_text="Pressure rise rate in 1/s", null=True),
        ),
        migrations.AddField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="pressure_rise_quantity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lbv_pressure_rises",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="evaluated_standard_deviation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="evaluated_standard_deviation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generic uncertainty", "Generic Uncertainty"),
                    (
                        "combined from scatter and reported uncertainty",
                        "Combined from Scatter and Reported Uncertainty",
                    ),
                    ("statistical scatter", "Statistical Scatter"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="evaluated_standard_deviation_sourcetype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="valuewithunit",
            name="evaluated_standard_deviation_type",
            field=models.CharField(
                blank=True,
                choices=[("absolute", "Absolute"), ("relative", "Relative")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="experimentdataset",
            name="experiment_type",
            field=models.CharField(
                choices=[
                    ("ignition delay", "Ignition Delay"),
                    (
                        "laminar burning velocity measurement",
                        "Laminar Burning Velocity Measurement",
                    ),
                    ("jet stirred reactor measurement", "Jet Stirred Reactor Measurement"),
                    ("outlet concentration measurement", "Outlet Concentration Measurement"),
                    (
                        "concentration time profile measurement",
                        "Concentration Time Profile Measurement",
                    ),
                    (
                        "burner stabilized flame speciation measurement",
                        "Burner Stabilized Flame Speciation Measurement",
                    ),
                    ("rate coefficient", "Rate Coefficient"),
                    ("thermochemical", "Thermochemical"),
                ],
                default="ignition delay",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ConcentrationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("species_name", models.CharField(db_index=True, max_length=255)),
                ("inchi", models.CharField(blank=True, max_length=500)),
                ("smiles", models.CharField(blank=True, max_length=500)),
                ("time_units", models.CharField(default="s", max_length=20)),
                (
                    "quantity_units",
                    models.CharField(
                        help_text="Species concentration units (e.g., mole fraction, ppm)",
                        max_length=50,
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        help_text="Array of [time, value] or [time, value, uncertainty] pairs"
                    ),
                ),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concentration_profiles",
                        to="chemked_database.concentrationtimeprofilemeasurementdatapoint",
                    ),
                ),
            ],
            options={
                "db_table": "chemked_concentration_profiles",
            },
        ),
    ]
