# Generated by Django 4.2.29 on 2026-03-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0017_commonproperties_environment_temperature_quantity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("successful_imports", models.JSONField(blank=True, default=list)),
                ("failed_imports", models.JSONField(blank=True, default=list)),
                ("skipped_imports", models.JSONField(blank=True, default=list)),
                ("contributor_name", models.CharField(blank=True, max_length=200)),
                ("contributor_orcid", models.CharField(blank=True, max_length=20)),
                ("pr_url", models.URLField(blank=True)),
                ("pr_number", models.PositiveIntegerField(blank=True, null=True)),
                ("branch", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "chemked_submission",
                "ordering": ["-created_at"],
            },
        ),
    ]
