# Generated by Django 4.2.29 on 2026-03-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0018_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonproperties",
            name="ignition_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temperature", "Temperature"),
                    ("pressure", "Pressure"),
                    ("OH", "OH"),
                    ("OH*", "OH*"),
                    ("CH", "CH"),
                    ("CH*", "CH*"),
                    ("NH3", "NH3"),
                    ("CHEX", "CHEX"),
                    ("OHEX", "OHEX"),
                    ("CO2", "CO2"),
                    ("N2O", "N2O"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ignitiondelaydatapoint",
            name="ignition_target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("temperature", "Temperature"),
                    ("pressure", "Pressure"),
                    ("OH", "OH"),
                    ("OH*", "OH*"),
                    ("CH", "CH"),
                    ("CH*", "CH*"),
                    ("NH3", "NH3"),
                    ("CHEX", "CHEX"),
                    ("OHEX", "OHEX"),
                    ("CO2", "CO2"),
                    ("N2O", "N2O"),
                ],
                help_text="Overrides dataset common ignition target if set",
                max_length=20,
            ),
        ),
    ]
