# Generated by Django 4.2.29 on 2026-03-30 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0019_alter_commonproperties_ignition_target_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concentrationprofile",
            name="inchi",
        ),
        migrations.RemoveField(
            model_name="concentrationprofile",
            name="smiles",
        ),
        migrations.RemoveField(
            model_name="concentrationprofile",
            name="species_name",
        ),
        migrations.AddField(
            model_name="concentrationprofile",
            name="species",
            field=models.ForeignKey(
                help_text="Tracked species for this concentration profile",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="concentration_profiles",
                to="chemked_database.compositionspecies",
            ),
        ),
    ]
