# Generated by Django 4.2.29 on 2026-03-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0020_remove_concentrationprofile_inchi_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fileauthor",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="fileauthor",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_file_author_name"),
        ),
    ]
