# Generated by Django 4.2.29 on 2026-03-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0021_fix_fileauthor_unique_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="measurement_type",
            field=models.CharField(
                choices=[
                    ("rate coefficient", "Rate Coefficient"),
                    ("branching ratio", "Branching Ratio"),
                ],
                default="rate coefficient",
                help_text="Type of measured quantity (rate coefficient, branching ratio)",
                max_length=30,
            ),
        ),
    ]
