# Generated by Django 4.2.29 on 2026-03-31 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0022_add_measurement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_sourcetype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_type",
            field=models.CharField(
                blank=True,
                choices=[("absolute", "Absolute"), ("relative", "Relative")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_quantity",
            field=models.ForeignKey(
                blank=True,
                help_text="Rich value container with uncertainty and evaluated standard deviation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_coefficient_datapoints",
                to="chemked_database.valuewithunit",
            ),
        ),
        migrations.AddField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_uncertainty_bound",
            field=models.CharField(
                blank=True,
                choices=[("plus", "Plus"), ("minus", "Minus"), ("plusminus", "Plus/Minus")],
                max_length=20,
            ),
        ),
    ]
