# Generated by Django 4.2.29 on 2026-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemked_database', '0023_add_rate_coefficient_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminarburningvelocitymeasurementdatapoint',
            name='laminar_burning_velocity_uncertainty_bound',
        ),
        migrations.RemoveField(
            model_name='ratecoefficientdatapoint',
            name='rate_coefficient_uncertainty_bound',
        ),
        migrations.RemoveField(
            model_name='valuewithunit',
            name='uncertainty_bound',
        ),
        migrations.AddField(
            model_name='ratecoefficientdatapoint',
            name='rate_coefficient_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ratecoefficientdatapoint',
            name='rate_coefficient_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
