# Generated by Django 4.2.29 on 2026-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemked_database', '0024_remove_uncertainty_bound'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonproperties',
            name='pressure_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonproperties',
            name='pressure_rise_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonproperties',
            name='pressure_rise_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonproperties',
            name='pressure_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdatapoint',
            name='pressure_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdatapoint',
            name='pressure_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdatapoint',
            name='temperature_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentdatapoint',
            name='temperature_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiondelaydatapoint',
            name='ignition_delay_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ignitiondelaydatapoint',
            name='ignition_delay_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laminarburningvelocitymeasurementdatapoint',
            name='laminar_burning_velocity_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laminarburningvelocitymeasurementdatapoint',
            name='laminar_burning_velocity_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmdata',
            name='compressed_pressure_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmdata',
            name='compressed_pressure_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmdata',
            name='compressed_temperature_lower_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcmdata',
            name='compressed_temperature_upper_uncertainty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
