# Generated by Django 4.2.29 on 2026-04-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemked_database', '0025_add_upper_lower_uncertainty_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonproperties',
            name='ignition_type',
            field=models.CharField(blank=True, choices=[('d/dt max', 'd/dt max'), ('max', 'max'), ('1/2 max', '1/2 max'), ('min', 'min'), ('d/dt max extrapolated', 'd/dt max extrapolated'), ('d/dt min extrapolated', 'd/dt min extrapolated'), ('relative concentration', 'Relative Concentration'), ('relative increase', 'Relative Increase')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ignitiondelaydatapoint',
            name='ignition_type',
            field=models.CharField(blank=True, choices=[('d/dt max', 'd/dt max'), ('max', 'max'), ('1/2 max', '1/2 max'), ('min', 'min'), ('d/dt max extrapolated', 'd/dt max extrapolated'), ('d/dt min extrapolated', 'd/dt min extrapolated'), ('relative concentration', 'Relative Concentration'), ('relative increase', 'Relative Increase')], help_text='Overrides dataset common ignition type if set', max_length=50),
        ),
    ]
