# Generated by Django 4.2.29 on 2026-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0027_add_ignition_target_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apparatus",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reflected shock", "Reflected Shock"),
                    ("incident shock", "Incident Shock"),
                    ("laminar", "Laminar"),
                    ("burner stabilized", "Burner Stabilized"),
                    ("constant volume combustion chamber", "Constant Volume Combustion Chamber"),
                    ("premixed", "Premixed"),
                    ("unstretched", "Unstretched"),
                    (
                        "extrapolation method to zero stretch : LS",
                        "Extrapolation to Zero Stretch (LS)",
                    ),
                    (
                        "extrapolation method to zero stretch : NQ",
                        "Extrapolation to Zero Stretch (NQ)",
                    ),
                    ("counterflow", "Counterflow"),
                    ("OPF", "OPF"),
                    ("HFM", "HFM"),
                    ("CTF", "CTF"),
                    ("SFF", "SFF"),
                ],
                db_column="operating_mode",
                help_text="Operating mode (e.g., 'reflected shock', 'premixed')",
                max_length=100,
            ),
        ),
    ]
