# Generated by Django 4.2.29 on 2026-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemked_database", "0028_rename_mode_column"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_rise_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_rise_uncertainty",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_rise_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_rise_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_uncertainty",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="commonproperties",
            name="pressure_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="pressure_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="pressure_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="pressure_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="pressure_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="temperature_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="temperature_uncertainty",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="temperature_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="experimentdatapoint",
            name="temperature_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ignitiondelaydatapoint",
            name="ignition_delay_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ignitiondelaydatapoint",
            name="ignition_delay_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ignitiondelaydatapoint",
            name="ignition_delay_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="ignitiondelaydatapoint",
            name="ignition_delay_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="laminar_burning_velocity_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="laminar_burning_velocity_uncertainty",
        ),
        migrations.RemoveField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="laminar_burning_velocity_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="laminarburningvelocitymeasurementdatapoint",
            name="laminar_burning_velocity_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_label",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_sourcetype",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="evaluated_standard_deviation_type",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_uncertainty",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="ratecoefficientdatapoint",
            name="rate_coefficient_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_pressure_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_pressure_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_pressure_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_pressure_upper_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_temperature_lower_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_temperature_uncertainty",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_temperature_uncertainty_type",
        ),
        migrations.RemoveField(
            model_name="rcmdata",
            name="compressed_temperature_upper_uncertainty",
        ),
        migrations.AlterField(
            model_name="evaluatedstandarddeviation",
            name="sourcetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reported", "Reported"),
                    ("estimated", "Estimated"),
                    ("calculated", "Calculated"),
                    ("digitized", "Digitized"),
                ],
                help_text="How the standard deviation was obtained",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="valuewithunit",
            name="evaluated_standard_deviation_sourcetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reported", "Reported"),
                    ("estimated", "Estimated"),
                    ("calculated", "Calculated"),
                    ("digitized", "Digitized"),
                ],
                help_text="How the evaluated standard deviation was obtained (reported, estimated, calculated, digitized)",
                max_length=100,
            ),
        ),
    ]
