# Generated by Django 4.2.29 on 2026-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
        ('chemked_database', '0029_remove_legacy_uncertainty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='institution_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apparatus', to='provenance.institution'),
        ),
        migrations.AddField(
            model_name='experimentdataset',
            name='data_repository_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experimentdataset',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='provenance.license'),
        ),
        migrations.AddField(
            model_name='fileauthor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provenance.person'),
        ),
        migrations.AddField(
            model_name='referenceauthor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='provenance.person'),
        ),
    ]
