#!/usr/bin/env python
# encoding: utf-8

name = "PCI2017/032-Cheng"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2017/032-Cheng
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.904,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c4h10 + ch3 <=> pc4h9 + ch4""",
)

entry(
    index = 1,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(349000,'cm^3/(mol*s)'), n=2.69, Ea=(6450,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c4h10 + h <=> pc4h9 + h2""",
)

entry(
    index = 2,
    label = "C2H5 + C2H4 <=> C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(13200,'cm^3/(mol*s)'), n=2.48, Ea=(6130,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c2h5 + c2h4 <=> pc4h9""",
)

entry(
    index = 3,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.837,'cm^3/(mol*s)'), n=3.59, Ea=(11960,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is pc4h9 + o2 <=> c4h8-1 + ho2""",
)

entry(
    index = 4,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'s^-1'), n=0, Ea=(31850,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is pc4h9o2 <=> c4h8ooh1-2""",
)

