#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2013/2343-Hansen"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2013/2343-Hansen
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(7.23e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is HO2 + C2H5 <=> H2O2 + C2H4""",
)

