# Generated by Django 4.2.24 on 2026-01-12

from django.db import migrations


def merge_duplicate_authors(apps, schema_editor):
    """
    Merge duplicate authors by reassigning authorships to the first author
    with each unique (firstname, lastname) combination, then delete duplicates.
    """
    Author = apps.get_model('database', 'Author')
    Authorship = apps.get_model('database', 'Authorship')
    
    # Find all unique (firstname, lastname) combinations
    seen = {}  # (firstname, lastname) -> primary author id
    duplicates_to_delete = []
    
    for author in Author.objects.all().order_by('id'):
        key = (author.firstname, author.lastname)
        if key in seen:
            # This is a duplicate - reassign authorships to the primary author
            primary_author_id = seen[key]
            
            # Update all authorships pointing to this duplicate
            Authorship.objects.filter(author_id=author.id).update(author_id=primary_author_id)
            
            # Mark for deletion
            duplicates_to_delete.append(author.id)
        else:
            # This is the first occurrence - keep it
            seen[key] = author.id
    
    # Delete duplicate authors
    if duplicates_to_delete:
        Author.objects.filter(id__in=duplicates_to_delete).delete()
        print(f"Merged and deleted {len(duplicates_to_delete)} duplicate author records.")


def reverse_merge(apps, schema_editor):
    """Cannot reverse a merge operation."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("database", "import_rmg_models"),
    ]

    operations = [
        migrations.RunPython(merge_duplicate_authors, reverse_merge),
    ]
