# Generated by Django 4.2.24 on 2026-01-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_merge_duplicate_authors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["lastname", "firstname"]},
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("firstname", "lastname")},
        ),
    ]
