# Generated by Django 5.2.17 on 2026-10-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_add_author_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='canonical_smiles',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='structure',
            name='iupac_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='names_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='pubchem_cid',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='StructureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='database.structure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('structure', 'name'), name='unique_structure_name')],
            },
        ),
    ]
