# Generated by Django 4.2.29 on 2026-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
        ('database', '0002_add_author_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_records', to='provenance.person'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kinetic_models', to='provenance.license'),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='model_format',
            field=models.CharField(blank=True, default='CHEMKIN', max_length=80),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='kineticmodel',
            name='zenodo_doi',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='provenance.license'),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
