# Generated by Django 5.2.17 on 2026-10-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_structure_search_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('atct', 'ATcT'), ('burcat', 'Burcat'), ('group_additivity', 'Group Additivity')], db_index=True, max_length=24)),
                ('external_id', models.CharField(max_length=500)),
                ('source_version', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=500)),
                ('phase', models.CharField(default='gas', max_length=20)),
                ('electronic_state', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('enthalpy_0', models.FloatField(blank=True, help_text='Formation enthalpy, J/mol', null=True)),
                ('enthalpy_298', models.FloatField(blank=True, help_text='Formation enthalpy at 298.15 K, J/mol', null=True)),
                ('uncertainty_298', models.FloatField(blank=True, help_text='Reported uncertainty, J/mol; see source convention', null=True)),
                ('entropy_298', models.FloatField(blank=True, help_text='Entropy at 298.15 K, J/(mol K)', null=True)),
                ('provenance', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('retrieved_at', models.DateTimeField(auto_now=True)),
                ('nasa_thermo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_record', to='database.thermo')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermo_records', to='database.species')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thermo_records', to='database.structure')),
            ],
            options={
                'ordering': ('provider', 'external_id', '-retrieved_at'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id', 'source_version'), name='unique_versioned_thermo_record')],
            },
        ),
    ]
