# Generated by Django 5.2.17 on 2026-10-05 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_thermo_source_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermoProviderStatus',
            fields=[
                ('provider', models.CharField(choices=[('atct', 'ATcT'), ('burcat', 'Burcat'), ('group_additivity', 'Group Additivity')], max_length=24, primary_key=True, serialize=False)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThermoEnrichmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('atct', 'ATcT'), ('burcat', 'Burcat'), ('group_additivity', 'Group Additivity')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Available'), ('no_match', 'No matching source record'), ('review', 'Needs identity/state review'), ('unsupported', 'Estimation unsupported'), ('failed', 'Failed; retry scheduled'), ('blocked', 'Source access blocked; retry scheduled')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.thermorecord')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermo_jobs', to='database.structure')),
            ],
            options={
                'ordering': ('structure_id', 'provider'),
                'indexes': [models.Index(fields=['provider', 'status', 'next_attempt_at'], name='thermo_job_due')],
                'constraints': [models.UniqueConstraint(fields=('structure', 'provider'), name='unique_structure_thermo_job')],
            },
        ),
    ]
