# Generated by Django 5.2.17 on 2026-10-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_thermo_enrichment_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="thermorecord",
            name="enthalpy_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constrained_by_enthalpy",
                to="database.thermorecord",
            ),
        ),
        migrations.AddField(
            model_name="thermorecord",
            name="heat_capacity_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constrained_by_heat_capacity",
                to="database.thermorecord",
            ),
        ),
        migrations.AlterField(
            model_name="thermoenrichmentjob",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="thermoproviderstatus",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                ],
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thermorecord",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
