# Generated by Django 5.2.17 on 2026-10-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_atct_constrained_thermo"),
    ]

    operations = [
        migrations.AddField(
            model_name="kinetics",
            name="rate_fingerprint",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reaction",
            name="canonical_direction",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reaction",
            name="canonical_key",
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="reaction",
            name="layer",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="structure",
            name="structure_key",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
