# Generated by Django 5.2.17 on 2026-10-06 05:34

import database.models.kinetic_data
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_chemical_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="rmg_family",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="reaction",
            name="rmg_template",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="thermoenrichmentjob",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                    ("rmg_thermo_library", "RMG-database thermo library"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="thermoproviderstatus",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                    ("rmg_thermo_library", "RMG-database thermo library"),
                ],
                max_length=24,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="thermorecord",
            name="provider",
            field=models.CharField(
                choices=[
                    ("atct", "ATcT"),
                    ("burcat", "Burcat"),
                    ("group_additivity", "Group Additivity"),
                    ("atct_constrained", "ATcT-constrained RMG thermo"),
                    ("rmg_thermo_library", "RMG-database thermo library"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="KineticsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_direction", models.SmallIntegerField(default=1)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("rmg_library", "RMG-database library"),
                            ("rmg_family", "RMG rate-rule estimate"),
                            ("nist", "NIST Chemical Kinetics Database"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "library",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="RMG library or family, or the NIST squib",
                        max_length=200,
                    ),
                ),
                ("external_id", models.CharField(max_length=500)),
                ("source_version", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=500)),
                (
                    "raw_data",
                    models.JSONField(
                        validators=[database.models.kinetic_data.validate_kinetics_data]
                    ),
                ),
                ("rate_fingerprint", models.JSONField(blank=True, null=True)),
                ("min_temp", models.FloatField(blank=True, help_text="K", null=True)),
                ("max_temp", models.FloatField(blank=True, help_text="K", null=True)),
                ("min_pressure", models.FloatField(blank=True, help_text="Pa", null=True)),
                ("max_pressure", models.FloatField(blank=True, help_text="Pa", null=True)),
                ("reference", models.TextField(blank=True)),
                ("short_desc", models.TextField(blank=True)),
                ("long_desc", models.TextField(blank=True)),
                ("provenance", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True, max_length=1000)),
                ("retrieved_at", models.DateTimeField(auto_now=True)),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kinetics_records",
                        to="database.reaction",
                    ),
                ),
            ],
            options={
                "ordering": ("provider", "library", "external_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id", "source_version"),
                        name="unique_versioned_kinetics_record",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelLibraryOverlap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("library", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("kinetics", "Reactions"), ("thermo", "Thermo")], max_length=10
                    ),
                ),
                ("source_version", models.CharField(max_length=100)),
                (
                    "model_total",
                    models.PositiveIntegerField(
                        help_text="The model's reactions (or species with thermo)"
                    ),
                ),
                ("shared", models.PositiveIntegerField(help_text="Of those, also in the library")),
                (
                    "identical",
                    models.PositiveIntegerField(
                        help_text="Of those, with the same rate (or thermo) as the library"
                    ),
                ),
                (
                    "kinetic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_overlaps",
                        to="database.kineticmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("kinetic_model", "kind", "-identical"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kinetic_model", "library", "kind"),
                        name="unique_model_library_overlap",
                    )
                ],
            },
        ),
    ]
