# Generated by Django 5.2.17 on 2026-10-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_rmg_counterparts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemistryBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("size", models.PositiveIntegerField(help_text="Reactions with identical rates")),
                ("layers", models.JSONField(default=dict, help_text="Reactions per layer")),
                (
                    "kinetic_models",
                    models.ManyToManyField(
                        related_name="chemistry_blocks", to="database.kineticmodel"
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Earliest-published model of the set (the likely source)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="originated_blocks",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "reactions",
                    models.ManyToManyField(related_name="chemistry_blocks", to="database.reaction"),
                ),
            ],
            options={
                "ordering": ("-size",),
            },
        ),
        migrations.CreateModel(
            name="SharedChemistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("layer", models.CharField(max_length=40)),
                ("reactions", models.PositiveIntegerField(help_text="A's reactions in this layer")),
                ("shared", models.PositiveIntegerField(help_text="Of those, also in B")),
                (
                    "identical",
                    models.PositiveIntegerField(
                        help_text="Of those, with a rate identical to one of B's"
                    ),
                ),
                (
                    "model_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_from",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "model_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_to",
                        to="database.kineticmodel",
                    ),
                ),
            ],
            options={
                "ordering": ("model_a", "layer", "-identical"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_a", "model_b", "layer"), name="unique_shared_chemistry"
                    )
                ],
            },
        ),
    ]
