# Generated by Django 5.2.17 on 2026-10-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_shared_chemistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(blank=True, help_text="Curated name, e.g. 'Aramco C1'. Kept when the analysis is rerun.", max_length=200)),
                ('default_name', models.CharField(help_text='Origin model and layer', max_length=200)),
                ('model_count', models.PositiveIntegerField(default=0)),
                ('variant_count', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0, help_text='Distinct reactions across all variants')),
                ('core', models.PositiveIntegerField(default=0, help_text='Reactions with the same rate in every variant')),
                ('cohesion', models.FloatField(default=0.0, help_text='Mean share of identical reactions between pairs of variants')),
                ('origin', models.ForeignKey(blank=True, help_text='Earliest-published model using it; its version is variant 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_sub_mechanisms', to='database.kineticmodel')),
            ],
            options={
                'ordering': ('layer', '-model_count', 'default_name'),
            },
        ),
        migrations.CreateModel(
            name='SubMechanismVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text="1 is the origin's version, then by publication year")),
                ('reactions', models.PositiveIntegerField()),
                ('identical', models.PositiveIntegerField(help_text='Reactions with the same rate as in variant 1')),
                ('added', models.PositiveIntegerField(help_text='Reactions variant 1 does not have')),
                ('missing', models.PositiveIntegerField(help_text='Reactions of variant 1 this version does not have')),
                ('kinetic_models', models.ManyToManyField(related_name='sub_mechanism_variants', to='database.kineticmodel')),
                ('representative', models.ForeignKey(help_text='Earliest-published model using this version', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='database.kineticmodel')),
                ('sub_mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='database.submechanism')),
            ],
            options={
                'ordering': ('sub_mechanism', 'number'),
                'constraints': [models.UniqueConstraint(fields=('sub_mechanism', 'number'), name='unique_variant_number')],
            },
        ),
    ]
