# Generated by Django 5.2.17 on 2026-10-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_sub_mechanisms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kineticsrecord',
            name='library',
            field=models.CharField(blank=True, db_index=True, help_text='RMG library or family', max_length=200),
        ),
        migrations.AlterField(
            model_name='kineticsrecord',
            name='provider',
            field=models.CharField(choices=[('rmg_library', 'RMG-database library'), ('rmg_family', 'RMG rate-rule estimate')], db_index=True, max_length=24),
        ),
    ]
