# Generated by Django 5.2.17 on 2026-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_drop_nist_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='cas_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='cas_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
