# Generated by Django 5.2.17 on 2026-10-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_structure_cas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='cas_checked_at',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='cas_numbers',
        ),
    ]
