#!/usr/bin/env python
# encoding: utf-8

name = "PCI2013/325-Husson"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2013/325-Husson
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R3OOH + R11C2H5 <=> C2H4Z + H2O2""",
)

entry(
    index = 1,
    label = "2C2H3O <=> C2H2O + C2H4O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R14CH3CO + R14CH3CO <=> CH2COZ + CH3CHO""",
)

entry(
    index = 2,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+10,'cm^3/(mol*s)'), n=0, Ea=(-1400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + R13CH2CHO <=> CH2COZ + R3OOH""",
)

