# Generated by Django 4.2.24 on 2026-02-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("database", "0002_add_author_unique_constraint"),
        ("chemked_database", "0015_alter_experimentdataset_experiment_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (User)"),
                            ("auto_model", "Auto (Model Updated)"),
                            ("auto_dataset", "Auto (Dataset Updated)"),
                            ("scheduled", "Scheduled"),
                            ("api", "API Request"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "model_version_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of model content at simulation time",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("skip_validation", models.BooleanField(default=True)),
                (
                    "spec_keys_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="Species mapping used for this run"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to="chemked_database.experimentdataset",
                    ),
                ),
                (
                    "kinetic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_runs",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_simulations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analysis_simulation_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "average_error_function",
                    models.FloatField(
                        blank=True,
                        help_text="Average error function value across all datapoints",
                        null=True,
                    ),
                ),
                (
                    "average_deviation_function",
                    models.FloatField(
                        blank=True,
                        help_text="Average deviation (log ratio) across all datapoints",
                        null=True,
                    ),
                ),
                (
                    "results_yaml",
                    models.TextField(blank=True, help_text="Raw YAML output from PyTeCK"),
                ),
                (
                    "results_json",
                    models.JSONField(blank=True, default=dict, help_text="Parsed results as JSON"),
                ),
                ("num_datapoints", models.PositiveIntegerField(default=0)),
                ("num_successful", models.PositiveIntegerField(default=0)),
                ("num_failed", models.PositiveIntegerField(default=0)),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("min_pressure", models.FloatField(blank=True, null=True)),
                ("max_pressure", models.FloatField(blank=True, null=True)),
                (
                    "simulation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="analysis.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_simulation_result",
            },
        ),
        migrations.CreateModel(
            name="ModelDatasetCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("latest_error_function", models.FloatField(blank=True, null=True)),
                ("latest_deviation", models.FloatField(blank=True, null=True)),
                ("has_successful_run", models.BooleanField(default=False)),
                (
                    "is_outdated",
                    models.BooleanField(
                        default=False, help_text="True if model changed since last run"
                    ),
                ),
                (
                    "needs_rerun",
                    models.BooleanField(default=False, help_text="Flagged for re-evaluation"),
                ),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("successful_runs", models.PositiveIntegerField(default=0)),
                ("failed_runs", models.PositiveIntegerField(default=0)),
                ("first_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_coverage",
                        to="chemked_database.experimentdataset",
                    ),
                ),
                (
                    "kinetic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_coverage",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "latest_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="analysis.simulationrun",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_model_dataset_coverage",
            },
        ),
        migrations.CreateModel(
            name="DatapointResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("temperature", models.FloatField(help_text="Temperature in Kelvin")),
                ("pressure", models.FloatField(help_text="Pressure in Pascal")),
                (
                    "composition",
                    models.JSONField(
                        default=list, help_text="Species composition at this datapoint"
                    ),
                ),
                ("composition_type", models.CharField(default="mole fraction", max_length=50)),
                (
                    "experimental_ignition_delay",
                    models.FloatField(help_text="Experimental ignition delay in seconds"),
                ),
                (
                    "simulated_ignition_delay",
                    models.FloatField(
                        blank=True, help_text="Simulated ignition delay in seconds", null=True
                    ),
                ),
                (
                    "error_value",
                    models.FloatField(
                        blank=True, help_text="Error function value for this datapoint", null=True
                    ),
                ),
                (
                    "deviation",
                    models.FloatField(
                        blank=True, help_text="Log deviation (simulated/experimental)", null=True
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "datapoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulation_results",
                        to="chemked_database.experimentdatapoint",
                    ),
                ),
                (
                    "simulation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datapoint_results",
                        to="analysis.simulationresult",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_datapoint_result",
                "ordering": ["temperature"],
            },
        ),
        migrations.CreateModel(
            name="SpeciesMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_species_name",
                    models.CharField(
                        help_text="Species name as it appears in the dataset", max_length=100
                    ),
                ),
                (
                    "model_species_name",
                    models.CharField(
                        help_text="Corresponding species name in the kinetic model", max_length=100
                    ),
                ),
                (
                    "mapping_method",
                    models.CharField(
                        choices=[
                            ("smiles", "SMILES Match"),
                            ("inchi", "InChI Match"),
                            ("normalized", "Normalized Label Match"),
                            ("manual", "Manual Override"),
                            ("fallback", "Fallback (Unverified)"),
                        ],
                        default="fallback",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5, help_text="Confidence score 0-1")),
                ("is_manual_override", models.BooleanField(default=False)),
                ("override_reason", models.CharField(blank=True, max_length=200)),
                ("smiles", models.CharField(blank=True, max_length=500)),
                ("inchi", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all datasets",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_mappings",
                        to="chemked_database.experimentdataset",
                    ),
                ),
                (
                    "kinetic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_mappings",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analysis_species_mapping",
                "indexes": [
                    models.Index(
                        fields=["kinetic_model", "dataset_species_name"],
                        name="analysis_sp_kinetic_8e128a_idx",
                    )
                ],
                "unique_together": {("kinetic_model", "dataset", "dataset_species_name")},
            },
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["kinetic_model", "dataset"], name="analysis_si_kinetic_057255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simulationrun",
            index=models.Index(
                fields=["status", "created_at"], name="analysis_si_status_9a69fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modeldatasetcoverage",
            index=models.Index(
                fields=["has_successful_run", "is_outdated"], name="analysis_mo_has_suc_369cb8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modeldatasetcoverage",
            unique_together={("kinetic_model", "dataset")},
        ),
    ]
