# Generated by Django 4.2.24 on 2026-02-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_add_author_unique_constraint"),
        ("analysis", "0002_simulationrun_results_dir"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'butanol isomers'",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Shared molecular formula, e.g. 'C4H10O'",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_auto",
                    models.BooleanField(
                        default=True, help_text="True if group was auto-generated from formula"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Lower numbers appear first"),
                ),
            ],
            options={
                "db_table": "analysis_fuel_group",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FuelSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "inchi",
                    models.CharField(
                        db_index=True,
                        help_text="Standard InChI (canonical key)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "smiles",
                    models.CharField(blank=True, help_text="Canonical SMILES", max_length=500),
                ),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Molecular formula, e.g. 'C7H16'",
                        max_length=50,
                    ),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Human-friendly name chosen from dataset species_name",
                        max_length=200,
                    ),
                ),
                (
                    "name_variants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of all species_name strings seen for this InChI",
                    ),
                ),
                (
                    "dataset_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of experiment datasets using this fuel"
                    ),
                ),
                (
                    "compatible_model_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of kinetic models that contain this species"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuels",
                        to="analysis.fuelgroup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "fuel species",
                "db_table": "analysis_fuel_species",
                "ordering": ["-dataset_count", "common_name"],
            },
        ),
        migrations.CreateModel(
            name="FuelModelCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_compatible", models.BooleanField(db_index=True, default=False)),
                (
                    "matched_model_species",
                    models.CharField(
                        blank=True,
                        help_text="Species name in the model that matched this fuel",
                        max_length=200,
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("smiles", "SMILES Match"),
                            ("inchi", "InChI Match"),
                            ("normalized", "Normalized Label Match"),
                            ("manual", "Manual Override"),
                            ("fallback", "Fallback (Unverified)"),
                        ],
                        default="fallback",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.FloatField(default=0.0, help_text="0-1 confidence of match"),
                ),
                (
                    "model_total_species",
                    models.PositiveIntegerField(
                        default=0, help_text="Total species count in the model"
                    ),
                ),
                (
                    "model_total_reactions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total reaction count in the model"
                    ),
                ),
                (
                    "species_mapping_snapshot",
                    models.JSONField(
                        blank=True, default=dict, help_text="Cached species mapping for preview"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fuel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_compatibilities",
                        to="analysis.fuelspecies",
                    ),
                ),
                (
                    "kinetic_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_compatibilities",
                        to="database.kineticmodel",
                    ),
                ),
                (
                    "latest_coverage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Best coverage record for any dataset with this fuel",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="analysis.modeldatasetcoverage",
                    ),
                ),
            ],
            options={
                "db_table": "analysis_fuel_model_compatibility",
                "indexes": [
                    models.Index(
                        fields=["is_compatible", "-match_confidence"],
                        name="analysis_fu_is_comp_19111a_idx",
                    ),
                    models.Index(
                        fields=["fuel", "is_compatible"], name="analysis_fu_fuel_id_a24945_idx"
                    ),
                ],
                "unique_together": {("fuel", "kinetic_model")},
            },
        ),
    ]
