# Generated by Django 4.2.24 on 2026-02-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_fuel_model_compatibility_map"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="fuelmodelcompatibility",
            name="analysis_fu_is_comp_19111a_idx",
        ),
        migrations.RemoveField(
            model_name="fuelmodelcompatibility",
            name="match_confidence",
        ),
    ]
