# Generated by Django 4.2.29 on 2026-06-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('database', '0002_add_author_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ror_id', models.CharField(blank=True, db_index=True, help_text='ROR identifier or URL, e.g. https://ror.org/00f54p054', max_length=255, verbose_name='ROR ID')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent organization (e.g. the university for a named lab).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='provenance.institution')),
            ],
            options={
                'db_table': 'provenance_institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spdx_id', models.CharField(help_text='SPDX identifier, e.g. MIT, BSD-3-Clause, CC-BY-4.0', max_length=100, unique=True, verbose_name='SPDX ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'provenance_license',
                'ordering': ['spdx_id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(blank=True, max_length=120)),
                ('family_name', models.CharField(blank=True, max_length=120)),
                ('full_name', models.CharField(blank=True, help_text='Display name when given/family cannot be split.', max_length=255)),
                ('orcid', models.CharField(blank=True, db_index=True, help_text='ORCID iD, e.g. 0000-0002-1825-0097', max_length=50, verbose_name='ORCID')),
                ('affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='provenance.institution')),
            ],
            options={
                'db_table': 'provenance_person',
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('inchikey', 'InChIKey'), ('inchi', 'InChI'), ('smiles', 'SMILES'), ('cas', 'CAS Registry Number'), ('pubchem.compound', 'PubChem CID'), ('CHEBI', 'ChEBI'), ('chembl', 'ChEMBL'), ('doi', 'DOI'), ('orcid', 'ORCID'), ('ror', 'ROR'), ('prime', 'PrIMe ID')], db_index=True, max_length=40)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'provenance_external_identifier',
            },
        ),
        migrations.CreateModel(
            name='SemanticMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_set_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('subject_id', models.CharField(db_index=True, max_length=255)),
                ('subject_label', models.CharField(blank=True, max_length=255)),
                ('predicate_id', models.CharField(default='skos:exactMatch', max_length=255)),
                ('object_id', models.CharField(db_index=True, max_length=255)),
                ('object_label', models.CharField(blank=True, max_length=255)),
                ('mapping_justification', models.CharField(blank=True, max_length=255)),
                ('subject_match_field', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('mapping_tool', models.CharField(blank=True, max_length=255)),
                ('mapping_date', models.DateField(blank=True, null=True)),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='database.species')),
            ],
            options={
                'db_table': 'provenance_semantic_mapping',
                'ordering': ['subject_id', '-confidence'],
                'indexes': [models.Index(fields=['subject_id'], name='provenance__subject_b0e838_idx'), models.Index(fields=['object_id'], name='provenance__object__f1a29a_idx'), models.Index(fields=['predicate_id'], name='provenance__predica_5c3995_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='semanticmapping',
            constraint=models.UniqueConstraint(fields=('subject_id', 'predicate_id', 'object_id'), name='provenance_unique_mapping'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('orcid__gt', '')), fields=('orcid',), name='provenance_unique_orcid'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='provenance_unique_institution'),
        ),
        migrations.AddIndex(
            model_name='externalidentifier',
            index=models.Index(fields=['content_type', 'object_id'], name='provenance__content_4f2992_idx'),
        ),
        migrations.AddIndex(
            model_name='externalidentifier',
            index=models.Index(fields=['scheme', 'value'], name='provenance__scheme_fd5350_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalidentifier',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'scheme', 'value'), name='provenance_unique_external_identifier'),
        ),
    ]
