# Generated by Django 4.2.29 on 2026-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
