# Generated by Django 4.2.29 on 2026-06-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_author_person_kineticmodel_created_at_and_more'),
        ('provenance', '0002_alter_person_family_name_alter_person_given_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticmapping',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='provenance.institution'),
        ),
        migrations.AddField(
            model_name='semanticmapping',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='provenance.person'),
        ),
        migrations.AddField(
            model_name='semanticmapping',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='database.source'),
        ),
    ]
