# Generated by Django 4.2.29 on 2026-06-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemked_database', '0030_apparatus_institution_ref_and_more'),
        ('provenance', '0005_semanticmapping_kinetic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticmapping',
            name='apparatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='chemked_database.apparatus'),
        ),
    ]
