# Generated by Django 4.2.29 on 2026-06-16 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_author_person_kineticmodel_created_at_and_more'),
        ('provenance', '0006_semanticmapping_apparatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanticmapping',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semantic_mappings', to='database.reaction'),
        ),
    ]
