# Generated by Django 4.2.24 on 2025-10-08 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusterJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Job name/path", max_length=500)),
                (
                    "port",
                    models.IntegerField(help_text="Port number for web interface", unique=True),
                ),
                (
                    "slurm_job_id",
                    models.CharField(
                        blank=True, help_text="SLURM job ID", max_length=50, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="Compute node running the job",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("total_species", models.IntegerField(default=0)),
                ("identified_species", models.IntegerField(default=0)),
                ("processed_species", models.IntegerField(default=0)),
                ("confirmed_species", models.IntegerField(default=0)),
                ("total_reactions", models.IntegerField(default=0)),
                ("unmatched_reactions", models.IntegerField(default=0)),
                ("last_log_update", models.DateTimeField(blank=True, null=True)),
                ("last_error_update", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Cluster Job",
                "verbose_name_plural": "Cluster Jobs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJobConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Configuration name", max_length=200, unique=True),
                ),
                (
                    "ssh_host",
                    models.CharField(
                        default="login.explorer.northeastern.edu",
                        help_text="SSH server hostname",
                        max_length=255,
                    ),
                ),
                ("ssh_port", models.IntegerField(default=22, help_text="SSH server port")),
                (
                    "root_path",
                    models.CharField(
                        default="/projects/westgroup/Importer/RMG-models/",
                        help_text="Root path for import jobs on cluster",
                        max_length=500,
                    ),
                ),
                (
                    "slurm_partition",
                    models.CharField(default="west", help_text="SLURM partition", max_length=100),
                ),
                (
                    "slurm_time_limit",
                    models.CharField(
                        default="3-00:00:00",
                        help_text="SLURM time limit (e.g., 3-00:00:00 for 3 days)",
                        max_length=50,
                    ),
                ),
                (
                    "slurm_memory",
                    models.CharField(
                        default="32768M",
                        help_text="SLURM memory allocation (e.g., 32768M for 32GB)",
                        max_length=50,
                    ),
                ),
                (
                    "slurm_extra_args",
                    models.TextField(blank=True, help_text="Additional SLURM arguments"),
                ),
                (
                    "conda_env_name",
                    models.CharField(
                        default="rmg_env", help_text="Conda environment name", max_length=100
                    ),
                ),
                (
                    "rmg_py_path",
                    models.CharField(
                        default="/projects/westgroup/lekia.p/RMG/RMG-Py",
                        help_text="Path to RMG-Py installation",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Use as default configuration"),
                ),
            ],
            options={
                "verbose_name": "Import Job Configuration",
                "verbose_name_plural": "Import Job Configurations",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Log",
                "verbose_name_plural": "Job Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configuration used for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="importer_dashboard.importjobconfig",
            ),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SpeciesIdentification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemkin_label",
                    models.CharField(help_text="Chemkin species label", max_length=200),
                ),
                ("smiles", models.CharField(help_text="SMILES string", max_length=500)),
                (
                    "rmg_species_label",
                    models.CharField(blank=True, help_text="RMG species label", max_length=200),
                ),
                (
                    "identification_method",
                    models.CharField(
                        default="manual", help_text="How species was identified", max_length=100
                    ),
                ),
                ("confidence", models.FloatField(default=1.0, help_text="Confidence score (0-1)")),
                ("vote_count", models.IntegerField(default=0, help_text="Number of votes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_identifications",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Identification",
                "verbose_name_plural": "Species Identifications",
                "ordering": ["-created_at"],
                "unique_together": {("job", "chemkin_label")},
            },
        ),
    ]
