# Generated by Django 4.2.24 on 2025-10-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterjob",
            name="tunnel_active",
            field=models.BooleanField(
                default=False, help_text="Whether SSH tunnel is currently active"
            ),
        ),
    ]
