# Generated by Django 4.2.24 on 2025-10-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("importer_dashboard", "0002_clusterjob_tunnel_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clusterjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemkin_label",
                    models.CharField(help_text="Label from Chemkin file", max_length=200),
                ),
                (
                    "formula",
                    models.CharField(help_text="Chemical formula (e.g., CH4)", max_length=100),
                ),
                (
                    "identification_status",
                    models.CharField(
                        choices=[
                            ("unidentified", "Unidentified"),
                            ("tentative", "Tentative Match"),
                            ("confirmed", "Confirmed"),
                            ("processed", "Processed"),
                        ],
                        default="unidentified",
                        max_length=20,
                    ),
                ),
                (
                    "rmg_label",
                    models.CharField(blank=True, help_text="RMG species label", max_length=200),
                ),
                (
                    "rmg_index",
                    models.IntegerField(blank=True, help_text="RMG species index", null=True),
                ),
                (
                    "smiles",
                    models.CharField(blank=True, help_text="SMILES representation", max_length=500),
                ),
                (
                    "enthalpy_discrepancy",
                    models.FloatField(
                        blank=True, help_text="H(298K) difference in kJ/mol", null=True
                    ),
                ),
                (
                    "identification_method",
                    models.CharField(
                        blank=True, help_text="auto, manual, vote, thermo", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "identified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identified_species",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["chemkin_label"],
                "unique_together": {("job", "chemkin_label")},
            },
        ),
        migrations.CreateModel(
            name="CandidateSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rmg_label", models.CharField(help_text="RMG species label", max_length=200)),
                ("rmg_index", models.IntegerField(help_text="RMG species index")),
                ("smiles", models.CharField(help_text="SMILES representation", max_length=500)),
                (
                    "enthalpy_discrepancy",
                    models.FloatField(help_text="H(298K) difference in kJ/mol"),
                ),
                (
                    "vote_count",
                    models.IntegerField(default=0, help_text="Number of voting reactions"),
                ),
                (
                    "unique_vote_count",
                    models.IntegerField(
                        default=0, help_text="Votes after pruning common reactions"
                    ),
                ),
                (
                    "thermo_library_matches",
                    models.IntegerField(default=0, help_text="Matches in thermo libraries"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, help_text="User blocked this match"),
                ),
                ("block_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="importer_dashboard.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidate Species",
                "verbose_name_plural": "Candidate Species",
                "ordering": ["-unique_vote_count", "-vote_count", "enthalpy_discrepancy"],
                "unique_together": {("species", "rmg_index")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "chemkin_reaction",
                    models.TextField(help_text="String representation of Chemkin reaction"),
                ),
                (
                    "rmg_reaction",
                    models.TextField(help_text="String representation of RMG reaction"),
                ),
                (
                    "rmg_reaction_family",
                    models.CharField(help_text="RMG reaction family", max_length=100),
                ),
                (
                    "is_unique",
                    models.BooleanField(
                        default=True, help_text="Not a common vote shared by multiple candidates"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="importer_dashboard.candidatespecies",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="importer_dashboard.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote",
                "verbose_name_plural": "Votes",
                "ordering": ["-created_at"],
                "unique_together": {("species", "candidate", "chemkin_reaction")},
            },
        ),
        migrations.CreateModel(
            name="ThermoMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("library_name", models.CharField(help_text="Thermo library name", max_length=200)),
                (
                    "library_species_name",
                    models.CharField(help_text="Species name in library", max_length=200),
                ),
                (
                    "name_matches",
                    models.BooleanField(
                        default=False, help_text="Library name matches Chemkin label"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thermo_matches",
                        to="importer_dashboard.candidatespecies",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thermo_matches",
                        to="importer_dashboard.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thermo Match",
                "verbose_name_plural": "Thermo Matches",
                "ordering": ["-name_matches", "library_name"],
                "unique_together": {("species", "candidate", "library_name")},
            },
        ),
        migrations.CreateModel(
            name="BlockedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chemkin_label", models.CharField(max_length=200)),
                ("smiles", models.CharField(max_length=500)),
                ("rmg_label", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_matches",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Match",
                "verbose_name_plural": "Blocked Matches",
                "ordering": ["-created_at"],
                "unique_together": {("job", "chemkin_label", "smiles")},
            },
        ),
    ]
