# Generated by Django 4.2.24 on 2025-10-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0003_alter_clusterjob_status_species_candidatespecies_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoteCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rmg_index", models.IntegerField(help_text="RMG species index")),
                ("smiles", models.CharField(help_text="SMILES representation", max_length=500)),
                (
                    "adjlist",
                    models.TextField(blank=True, help_text="Adjacency list representation"),
                ),
                (
                    "vote_count",
                    models.IntegerField(default=0, help_text="Number of voting reactions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_candidates",
                        to="importer_dashboard.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vote Candidate",
                "verbose_name_plural": "Vote Candidates",
                "ordering": ["-vote_count"],
                "unique_together": {("species", "rmg_index")},
            },
        ),
        migrations.CreateModel(
            name="VotingReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chemkin_reaction", models.TextField(help_text="Chemkin reaction string")),
                ("rmg_reaction", models.TextField(help_text="RMG reaction string")),
                (
                    "family",
                    models.CharField(blank=True, help_text="RMG reaction family", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_reactions",
                        to="importer_dashboard.votecandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voting Reaction",
                "verbose_name_plural": "Voting Reactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
