# Generated by Django 4.2.24 on 2025-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0004_votecandidate_votingreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatespecies",
            name="is_confirmed",
            field=models.BooleanField(default=False, help_text="User confirmed this match"),
        ),
    ]
