# Generated by Django 4.2.24 on 2025-10-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0005_candidatespecies_is_confirmed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidatespecies",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="candidatespecies",
            name="rmg_index",
            field=models.IntegerField(blank=True, help_text="RMG species index", null=True),
        ),
        migrations.AddConstraint(
            model_name="candidatespecies",
            constraint=models.UniqueConstraint(
                condition=models.Q(("rmg_index__isnull", False)),
                fields=("species", "rmg_index"),
                name="unique_species_rmg_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatespecies",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_confirmed", True), ("rmg_index__isnull", True)),
                fields=("species", "smiles"),
                name="unique_confirmed_species_smiles",
            ),
        ),
    ]
