# Generated by Django 4.2.24 on 2025-10-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0006_alter_candidatespecies_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatespecies",
            name="label_source",
            field=models.CharField(
                choices=[("rmg", "RMG Generated"), ("chemkin", "Chemkin File")],
                default="rmg",
                help_text="Source of the species label",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="candidatespecies",
            name="enthalpy_discrepancy",
            field=models.FloatField(
                blank=True, help_text="H(298K) difference in kJ/mol", null=True
            ),
        ),
    ]
