# Generated by Django 4.2.24 on 2025-10-27 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0007_candidatespecies_label_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        help_text="Type of data synced (votes, identified_species, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("pull", "Pull from cluster"), ("push", "Push to cluster")],
                        default="pull",
                        max_length=10,
                    ),
                ),
                (
                    "record_count",
                    models.IntegerField(default=0, help_text="Number of records synced"),
                ),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "synced_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-synced_at"],
                "indexes": [
                    models.Index(
                        fields=["job", "sync_type", "-synced_at"],
                        name="importer_da_job_id_b7f985_idx",
                    ),
                    models.Index(
                        fields=["job", "success", "-synced_at"],
                        name="importer_da_job_id_cda342_idx",
                    ),
                ],
            },
        ),
    ]
