# Generated by Django 4.2.24 on 2025-10-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0008_synclog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemkinThermo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("temp_low", models.FloatField(help_text="Lowest temperature (K)")),
                (
                    "temp_mid",
                    models.FloatField(help_text="Middle temperature for polynomial switch (K)"),
                ),
                ("temp_high", models.FloatField(help_text="Highest temperature (K)")),
                ("high_a1", models.FloatField()),
                ("high_a2", models.FloatField()),
                ("high_a3", models.FloatField()),
                ("high_a4", models.FloatField()),
                ("high_a5", models.FloatField()),
                ("high_a6", models.FloatField()),
                ("high_a7", models.FloatField()),
                ("low_a1", models.FloatField()),
                ("low_a2", models.FloatField()),
                ("low_a3", models.FloatField()),
                ("low_a4", models.FloatField()),
                ("low_a5", models.FloatField()),
                ("low_a6", models.FloatField()),
                ("low_a7", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemkin_thermo",
                        to="importer_dashboard.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "CHEMKIN Thermodynamics",
                "verbose_name_plural": "CHEMKIN Thermodynamics",
            },
        ),
        migrations.CreateModel(
            name="ChemkinReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.IntegerField(help_text="Reaction number in mechanism file")),
                (
                    "equation",
                    models.TextField(
                        help_text="Full reaction equation (e.g., 'H + O2 <=> O + OH')"
                    ),
                ),
                (
                    "reactants",
                    models.TextField(help_text="Comma-separated reactant species labels"),
                ),
                ("products", models.TextField(help_text="Comma-separated product species labels")),
                ("A", models.FloatField(help_text="Pre-exponential factor")),
                ("A_units", models.CharField(blank=True, help_text="Units for A", max_length=50)),
                ("n", models.FloatField(help_text="Temperature exponent")),
                ("Ea", models.FloatField(help_text="Activation energy")),
                (
                    "Ea_units",
                    models.CharField(
                        blank=True, help_text="Units for Ea (e.g., 'kcal/mol')", max_length=50
                    ),
                ),
                (
                    "temp_min",
                    models.FloatField(blank=True, help_text="Minimum temperature (K)", null=True),
                ),
                (
                    "temp_max",
                    models.FloatField(blank=True, help_text="Maximum temperature (K)", null=True),
                ),
                ("is_reversible", models.BooleanField(default=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("is_pressure_dependent", models.BooleanField(default=False)),
                (
                    "family",
                    models.CharField(blank=True, help_text="RMG reaction family", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemkin_reactions",
                        to="importer_dashboard.clusterjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "CHEMKIN Reaction",
                "verbose_name_plural": "CHEMKIN Reactions",
                "ordering": ["job", "index"],
                "indexes": [
                    models.Index(fields=["job", "index"], name="importer_da_job_id_de5398_idx"),
                    models.Index(
                        fields=["job", "is_duplicate"], name="importer_da_job_id_9d0e90_idx"
                    ),
                ],
                "unique_together": {("job", "index")},
            },
        ),
    ]
