# Generated by Django 4.2.24 on 2026-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_dashboard', '0010_importjobconfig_ood_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjobconfig',
            name='ood_allow_insecure_ssl',
            field=models.BooleanField(default=False, help_text='If enabled, disables SSL certificate verification for OOD progress fetching. Not recommended; use only as a temporary workaround.'),
        ),
        migrations.AddField(
            model_name='importjobconfig',
            name='ood_ca_bundle',
            field=models.CharField(blank=True, default='', help_text='Optional path to a CA bundle file to trust when fetching via OOD HTTPS. Use this if your environment cannot verify the OOD certificate chain.', max_length=500),
        ),
    ]
