# Generated by Django 4.2.24 on 2026-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_dashboard', '0011_importjobconfig_ood_allow_insecure_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjobconfig',
            name='ood_request_headers',
            field=models.TextField(blank=True, default='', help_text='Optional extra HTTP headers (one per line, as "Header-Name: value") to include when fetching OOD URLs. Useful for supplying an OOD session cookie, e.g.\nCookie: _ood_session=...'),
        ),
    ]
