# Generated by Django 4.2.24 on 2026-01-02 18:39

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('importer_dashboard', '0012_importjobconfig_ood_request_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterjob',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port number for web interface (optional until assigned)', null=True),
        ),
        migrations.AddConstraint(
            model_name='clusterjob',
            constraint=models.UniqueConstraint(condition=Q(('port__isnull', False)), fields=('config', 'port'), name='unique_clusterjob_port_per_config_when_set'),
        ),
    ]
