# Generated by Django 4.2.24 on 2026-01-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0013_alter_clusterjob_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterjob",
            name="matched_reactions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="tentative_species",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="thermo_matches_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="unidentified_species",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="unprocessed_species",
            field=models.IntegerField(default=0),
        ),
    ]
