# Generated by Django 4.2.24 on 2026-01-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0014_add_tentative_unidentified_species_to_clusterjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="identified_by_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Username or 'Auto' from cluster database",
                max_length=100,
            ),
        ),
    ]
