# Generated by Django 4.2.24 on 2026-01-08

from django.db import migrations


def deduplicate_confirmed_candidates(apps, schema_editor):
    """
    Remove duplicate confirmed CandidateSpecies entries.
    Keep only one confirmed candidate per (species, smiles) pair.
    """
    CandidateSpecies = apps.get_model('importer_dashboard', 'CandidateSpecies')
    
    # Get all confirmed candidates grouped by species and smiles
    from django.db.models import Count
    
    duplicates = (
        CandidateSpecies.objects
        .filter(is_confirmed=True)
        .values('species_id', 'smiles')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    
    deleted_count = 0
    for dup in duplicates:
        species_id = dup['species_id']
        smiles = dup['smiles']
        
        # Get all candidates with this species/smiles combo
        candidates = list(
            CandidateSpecies.objects
            .filter(species_id=species_id, smiles=smiles, is_confirmed=True)
            .order_by('-updated_at', 'id')  # Keep most recently updated
        )
        
        if len(candidates) > 1:
            # Keep the first one (most recently updated), delete the rest
            keep = candidates[0]
            for candidate in candidates[1:]:
                candidate.delete()
                deleted_count += 1
    
    print(f"Deduplicated {deleted_count} confirmed candidate entries")


def reverse_deduplicate(apps, schema_editor):
    """Cannot reverse deduplication"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0015_add_identified_by_name"),
    ]

    operations = [
        migrations.RunPython(deduplicate_confirmed_candidates, reverse_deduplicate),
    ]
