# Generated by Django 4.2.29 on 2026-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importer_dashboard", "0016_deduplicate_confirmed_candidates"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusterjob",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for local execution",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clusterjob",
            name="worker_pid",
            field=models.IntegerField(
                blank=True, help_text="OS process ID of the running import", null=True
            ),
        ),
    ]
