#!/usr/bin/env python
# encoding: utf-8

name = "CombFlame2013/1609-Veloo"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model CombFlame2013/1609-Veloo
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c2h5 + ho2 <=> c2h4 + h2o2""",
)

entry(
    index = 1,
    label = "C2H5 + C2H4 <=> C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.5e+11,'cm^3/(mol*s)'), n=0, Ea=(7300,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c2h4 + c2h5 <=> pc4h9""",
)

entry(
    index = 2,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.7e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is pc4h9 + o2 <=> c4h81 + ho2""",
)

entry(
    index = 3,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(920000,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c4h10 + h <=> pc4h9 + h2""",
)

entry(
    index = 4,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.903,'cm^3/(mol*s)'), n=3.65, Ea=(7153,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is c4h10 + ch3 <=> pc4h9 + ch4""",
)

entry(
    index = 5,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.58e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is ch2cho + o2 <=> ch2co + ho2""",
)

