#!/usr/bin/env python
# encoding: utf-8

name = "PCI2019/555-Sun"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2019/555-Sun
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(349000,'cm^3/(mol*s)'), n=2.69, Ea=(6450,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H <=> PC4H9 + H2""",
)

entry(
    index = 1,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.904,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + CH3 <=> PC4H9 + CH4""",
)

entry(
    index = 2,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.837,'cm^3/(mol*s)'), n=3.59, Ea=(11960,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9 + O2 <=> C4H8-1 + HO2""",
)

entry(
    index = 3,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4.009e+08,'s^-1'), n=1.1, Ea=(30100,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PC4H9O2 <=> C4H8OOH1-2""",
)

entry(
    index = 4,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5.26e+17,'cm^3/(mol*s)'), n=-1.638, Ea=(869,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is SC2H2OH + O2 <=> CH2CO + HO2""",
)

