#!/usr/bin/env python
# encoding: utf-8

name = "PCI2013/289-Dagaut"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2013/289-Dagaut
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(5e+11,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + CH2CHO => HO2 + CH2CO""",
)

entry(
    index = 1,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(4e+11,'cm^3/(mol*s)'), n=0, Ea=(3000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + NC4H9P => HO2 + NC4H8""",
)

entry(
    index = 2,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(9.5e+13,'cm^3/(mol*s)'), n=0, Ea=(10500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is H + NC4H10 <=> H2 + NC4H9P""",
)

entry(
    index = 3,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2e+11,'s^-1'), n=0, Ea=(20000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is NC4H9-OO => NC4-QOOH""",
)

entry(
    index = 4,
    label = "C4H9 + H2O2 -> HO2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(10830,'cm^3/(mol*s)'), n=2, Ea=(2037.98,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is NC4H9P + H2O2 => NC4H10 + HO2""",
)

entry(
    index = 5,
    label = "CH4O2 + C4H9 -> CH3O2 + C4H10",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(27070,'cm^3/(mol*s)'), n=2, Ea=(6911.81,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is NC4H9P + CH3OOH => NC4H10 + CH3OO""",
)

entry(
    index = 6,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(234200,'cm^3/(mol*s)'), n=2, Ea=(7545.23,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH3 + NC4H10 => CH4 + NC4H9P""",
)

