#!/usr/bin/env python
# encoding: utf-8

name = "PCI2017/111-Jin"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2017/111-Jin
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.33e+06,'cm^3/(mol*s)'), n=2.54, Ea=(6756,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H <=> pC4H9 + H2""",
)

entry(
    index = 1,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.906,'cm^3/(mol*s)'), n=3.65, Ea=(7154,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + CH3 <=> pC4H9 + CH4""",
)

entry(
    index = 2,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.4e+10,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is iC4H9 + O2 <=> iC4H8 + HO2""",
)

entry(
    index = 3,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5 + HO2 <=> C2H4 + H2O2""",
)

entry(
    index = 4,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.4e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CH2CHO + O2 <=> CH2CO + HO2""",
)

