#!/usr/bin/env python
# encoding: utf-8

name = "PCI2019/639-Cai"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2019/639-Cai
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C2H5 + HO2 <=> C2H4 + H2O2""",
)

entry(
    index = 1,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(188000,'cm^3/(mol*s)'), n=2.75, Ea=(6280.11,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is C4H10 + H => PXC4H9 + H2""",
)

entry(
    index = 2,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(2.5e+10,'s^-1'), n=0, Ea=(20849.9,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is PXC4H9O2 => C4H8OOH1X3""",
)

entry(
    index = 3,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(0.837,'cm^3/(mol*s)'), n=3.59, Ea=(11960.1,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is TXC4H9 + O2 => IXC4H8 + HO2""",
)

