"""
Django settings for kms project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
root = Path(__file__).resolve().parent.parent
prod_path = root / ".env"
dev_path = root / ".env.dev"
if prod_path.exists():
    load_dotenv(dotenv_path=prod_path)
else:
    load_dotenv(dotenv_path=dev_path)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(" ")


# Application definition

INSTALLED_APPS = [
    "livequery.apps.LiveQueryConfig",
    "analysis.apps.AnalysisConfig",
    "chemked_database.apps.ChemkedDatabaseConfig",
    "importer_dashboard.apps.ImporterDashboardConfig",
    # "import_voting.apps.ImportVotingConfig",  # REMOVED: Duplicate of importer_dashboard functionality
    "database.apps.DatabaseConfig",
    "api.apps.ApiConfig",
    "dal",
    "dal_select2",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "django_extensions",
    "crispy_forms",
    "crispy_bootstrap4",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    'mathfilters',
    'django_celery_results',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "kms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'kms', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "kms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": int(os.getenv("DB_PORT", 5432)),
        "OPTIONS": {
            "options": "-c timezone=utc"
        }
    }
}

# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.getenv("DATABASE_URL"),
#         conn_max_age=600,
#         options={'options': '-c timezone=utc'}
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

CRISPY_TEMPLATE_PACK = "bootstrap4"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    # Public read access by default. Write endpoints tighten this explicitly:
    # data viewsets require IsAdminUser to write, and the contribution endpoints
    # require IsAuthenticated.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    # Paginate list responses so endpoints never return an entire table at once.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "10000/day", "user": "100000/day"},
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Prometheus Kinetic Models API",
    "DESCRIPTION": (
        "FAIR REST API for the Prometheus combustion-kinetics cyberinfrastructure: "
        "canonical species, isomers, formulae, reactions, thermochemistry, transport, "
        "kinetics, and kinetic models. Read access is public; contributing data requires "
        "authentication."
    ),
    "VERSION": "1.0.0",
    # The first SERVERS entry is the base URL used in the generated code samples
    # and as the Swagger "Servers" default. (Optionally add a LICENSE entry.)
    "SERVERS": [
        {"url": "https://dev.omethe.us", "description": "Production"},
        {"url": "http://localhost:8000", "description": "Local development"},
    ],
    "CONTACT": {
        "name": "Prometheus Cyberinfrastructure",
        "url": "https://dev.omethe.us",
    },
    "EXTERNAL_DOCS": {
        "description": "Platform & API documentation",
        "url": "https://dev.omethe.us/docs/",
    },
    "POSTPROCESSING_HOOKS": [
        # Keep the default enum hook, then append our additions.
        "drf_spectacular.hooks.postprocess_schema_enums",
        "api.schema_hooks.add_field_examples",
        "api.schema_hooks.fix_pagination_urls",
        "api.schema_hooks.add_code_samples",
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "deepLinking": True,
        "displayRequestDuration": True,
        "filter": True,
        "tryItOutEnabled": True,
        "requestSnippetsEnabled": True,
    },
    "SERVE_INCLUDE_SCHEMA": False,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    # Self-host the Swagger UI and ReDoc assets via drf-spectacular-sidecar
    # instead of loading them from a public CDN (works offline / behind CSP /
    # behind the Cloudflare tunnel, with a pinned asset version).
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "COMPONENT_SPLIT_REQUEST": True,
    "ENUM_NAME_OVERRIDES": {
        "MappingMethodEnum": "analysis.models.MappingMethod",
        "UncertaintyTypeEnum": "chemked_database.models.UncertaintyType",
        "PropertySourceTypeEnum": "chemked_database.models.PropertySourceType",
        "EvaluatedStandardDeviationMethodEnum": "chemked_database.models.EvaluatedStandardDeviationMethod",
    },
    "TAGS": [
        {"name": "species", "description": "Canonical species, isomers, formulae, and structures."},
        {"name": "reactions", "description": "Reactions and their rate coefficients."},
        {"name": "models", "description": "Kinetic models and their assembled components."},
        {"name": "thermo-transport", "description": "Thermochemistry and transport properties."},
        {"name": "bibliography", "description": "Literature sources and authors."},
        {"name": "experimental-data", "description": "ChemKED experimental datasets and datapoints (read-only)."},
        {"name": "analysis", "description": "Simulation runs, results, and model-vs-data agreement (read-only)."},
        {"name": "contribute", "description": "Authenticated data-contribution endpoints."},
    ],
}

TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"
SILENCE_RMG_IMPORT_LOGS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        # Silence RMG import noise during tests/development
        'database.scripts.import_rmg_models': {
            'handlers': ['console'],
            'level': 'CRITICAL',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'CRITICAL' if TESTING else 'WARNING',
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
}

# Allow large batch uploads of ReSpecTh/ChemKED files
DATA_UPLOAD_MAX_NUMBER_FILES = 5000
# Increase memory limits for large batch uploads (100 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100 MB

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # or 'America/New_York'
CELERY_TASK_TRACK_STARTED = True

# Long-running import jobs need longer timeouts
CELERY_TASK_TIME_LIMIT = 3 * 24 * 3600      # Hard limit: 3 days (matches your SLURM --time=3-00:00:00)
CELERY_TASK_SOFT_TIME_LIMIT = 3 * 24 * 3600 - 300  # Soft limit: 3 days minus 5 min for cleanup
CELERY_WORKER_CONCURRENCY = 2                # Limit concurrent imports (RMG is memory-heavy ~32GB each)
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 40_000_000  # Kill worker if it exceeds ~40GB (KB)

# RMG/Importer paths on the office server
RMG_PY_PATH = os.getenv('RMGpy', '/home/prometheus/Importer/RMG-Py')
RMG_DATABASE_PATH = os.getenv('RMG_DATABASE_PATH', '/home/prometheus/Importer/RMG-database')
RMG_MODELS_PATH = os.getenv('RMGMODELSPATH', '/home/prometheus/Importer/RMG-models')
CONDA_ENV_NAME = os.getenv('CONDA_ENV_NAME', 'rmg_env')
CONDA_BASE_PATH = os.getenv('CONDA_BASE_PATH', '/home/prometheus/miniconda3')

# 'local' = Celery on office server, 'cluster' = SSH/SLURM on Explorer
IMPORTER_MODE = 'local'

# Celery Beat: periodic tasks (requires running `celery -A kms beat`)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'refresh-job-statuses': {
        'task': 'importer_dashboard.refresh_all_job_statuses',
        'schedule': 30.0,  # Every 30 seconds
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --------------------------------------------------------------------------
# GitHub Contribution Integration
# --------------------------------------------------------------------------
# These are used by the contribution workflow (chemked_database/github_pr_service.py)
# to create PRs on the ChemKED-database repository.
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
GITHUB_REPO_OWNER = os.getenv('GITHUB_REPO_OWNER', '')
GITHUB_REPO_NAME = os.getenv('GITHUB_REPO_NAME', 'ChemKED-database')

# Silence noisy RDKit warnings during imports/tests (e.g., unusual valence warnings)
try:
    from rdkit import RDLogger

    RDLogger.DisableLog('rdApp.warning')
except Exception:
    pass
