#!/usr/bin/env python
# encoding: utf-8

name = "MatheuCH4"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model MatheuCH4
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C4H9 + C3H5 <=> C3H6 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+12,'cm^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is CCC.C + C*CC. <=> C*CCC + C*CC""",
)

