"""Export the *value records* of the data layer as static linked data.

The lean ``prometheus.data.ttl`` index only says *which* thermo/transport/kinetics
records belong to each species/reaction (``prom:X pmtx:hasThermo promthermo:<pk>``).
To read the actual numbers an agent would otherwise have to dereference every
record IRI (``/thermo/<pk>`` etc.) with an RDF ``Accept`` header -- something a
plain crawler or a human pasting the URL into a browser will not do (the browser
gets the HTML detail page).

This command serialises the full numeric layer once: for every species/reaction
that has an SSSOM node it emits the same triples the live resolver produces via
``_emit_thermo`` / ``_emit_transport`` / ``_emit_kinetics`` -- NASA polynomials,
Lennard-Jones parameters, Arrhenius / Troe / PLOG / Chebyshev coefficients, with
QUDT units and ``prov:wasDerivedFrom`` model attribution -- into a single
``prometheus.records.ttl``.  Loading that file alongside the other layers gives an
agent the complete species -> record -> value -> model chain offline, no
content negotiation required.

The emit helpers are imported from ``provenance.resolver`` so this static dump is
guaranteed byte-for-byte consistent with what dereferencing a record returns.

Read-only against the database; idempotent (overwrites the file).
"""

from pathlib import Path

from django.core.management.base import BaseCommand
from rdflib import Graph, URIRef

from provenance import resolver
from provenance.models import SemanticMapping

MAPPINGS_DIR = Path(__file__).resolve().parents[4] / "mappings"
DEFAULT_TTL = MAPPINGS_DIR / "prometheus.records.ttl"

HEADER = (
    "# Prometheus data records: the full numeric thermo/transport/kinetics layer.\n"
    "# Every species/reaction SSSOM node links to its value records, each carrying\n"
    "# the actual coefficients (NASA polynomials, Lennard-Jones, Arrhenius/Troe/\n"
    "# PLOG/Chebyshev) as QUDT quantities + prov:wasDerivedFrom model attribution.\n"
    "# Identical to dereferencing the record IRIs; load with the other layers for\n"
    "# the complete species -> record -> value -> model chain offline.\n"
    "# Generated by `manage.py export_data_records` -- do not edit by hand.\n"
)


class Command(BaseCommand):
    help = (
        "Export the full numeric data layer (thermo/transport/kinetics VALUES) "
        "for every species/reaction with an SSSOM node into prometheus.records.ttl."
    )

    def add_arguments(self, parser):
        parser.add_argument("--ttl", default=str(DEFAULT_TTL))
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Report record counts without writing the file.",
        )

    def _anchors(self):
        """species_id -> prom: IRI and reaction_id -> promrxn: IRI."""
        sp_anchor = {}
        rxn_anchor = {}
        for r in SemanticMapping.objects.filter(
            species__isnull=False, subject_id__startswith="prom:"
        ).values("species_id", "subject_id"):
            sp_anchor.setdefault(r["species_id"], resolver._expand(r["subject_id"]))
        for r in SemanticMapping.objects.filter(reaction__isnull=False).values(
            "reaction_id", "subject_id"
        ):
            rxn_anchor.setdefault(r["reaction_id"], resolver._expand(r["subject_id"]))
        return sp_anchor, rxn_anchor

    def handle(self, *args, **options):
        from database.models import Kinetics, Thermo, Transport
        from database.models.kinetic_model import (
            KineticsComment,
            ThermoComment,
            TransportComment,
        )

        sp_anchor, rxn_anchor = self._anchors()

        g = Graph()
        resolver._bind_prefixes(g)
        counts = {"thermo": 0, "transport": 0, "kinetics": 0}

        # Species -> thermo records (full NASA polynomials).
        thermos = list(Thermo.objects.filter(species_id__in=sp_anchor.keys()))
        thermo_models = resolver._record_model_map(
            ThermoComment, "thermo_id", [t.id for t in thermos]
        )
        for t in thermos:
            subj = URIRef(sp_anchor[t.species_id])
            resolver._emit_thermo(g, subj, t, thermo_models.get(t.id, ()))
            counts["thermo"] += 1

        # Species -> transport records (Lennard-Jones parameters).
        transports = list(Transport.objects.filter(species_id__in=sp_anchor.keys()))
        transport_models = resolver._record_model_map(
            TransportComment, "transport_id", [t.id for t in transports]
        )
        for tr in transports:
            subj = URIRef(sp_anchor[tr.species_id])
            resolver._emit_transport(g, subj, tr, transport_models.get(tr.id, ()))
            counts["transport"] += 1

        # Reaction -> kinetics records (rate coefficients).
        kinetics = list(Kinetics.objects.filter(reaction_id__in=rxn_anchor.keys()))
        kinetics_models = resolver._record_model_map(
            KineticsComment, "kinetics_id", [k.id for k in kinetics]
        )
        for k in kinetics:
            subj = URIRef(rxn_anchor[k.reaction_id])
            resolver._emit_kinetics(g, subj, k, kinetics_models.get(k.id, ()))
            counts["kinetics"] += 1

        self.stdout.write("Value records emitted (with full coefficients):")
        for kind in ("thermo", "transport", "kinetics"):
            self.stdout.write(f"  {kind:10s} {counts[kind]}")
        self.stdout.write(f"  {'triples':10s} {len(g)}")

        if options["dry_run"]:
            self.stdout.write(self.style.WARNING("Dry run: no file written."))
            return

        path = Path(options["ttl"])
        body = g.serialize(format="turtle")
        if isinstance(body, bytes):
            body = body.decode("utf-8")
        path.write_text(HEADER + "\n" + body, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {options['ttl']}"))
