#!/usr/bin/env python
# encoding: utf-8

name = "PCI2013/297-Herbinet"
shortDesc = "Kinetics library for reactions shared with Harris-Butane"
longDesc = """
Kinetics entries from model PCI2013/297-Herbinet
filtered to reactions whose equation also appears in Harris-Butane.
Auto-generated from the kinetic-models database.
"""
autoGenerated = True

entry(
    index = 0,
    label = "C2H5 + HO2 <=> H2O2 + C2H4",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3e+11,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R3OOH + R11C2H5 <=> C2H4Z + H2O2""",
)

entry(
    index = 1,
    label = "2C2H3O <=> C2H2O + C2H4O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R14CH3CO + R14CH3CO <=> CH2COZ + CH3CHO""",
)

entry(
    index = 2,
    label = "C2H3O + O2 <=> HO2 + C2H2O",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1e+10,'cm^3/(mol*s)'), n=0, Ea=(-1400,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is O2 + R13CH2CHO <=> CH2COZ + R3OOH""",
)

entry(
    index = 3,
    label = "C4H9O2 <=> C4H9O2",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(3.3e+09,'s^-1'), n=1, Ea=(32500,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R32C4H9O2U <=> R44C4H9O2P""",
)

entry(
    index = 4,
    label = "C4H9 + O2 <=> HO2 + C4H8",
    degeneracy = 1.0,
    kinetics = Arrhenius(A=(1.3e+12,'cm^3/(mol*s)'), n=0, Ea=(5000,'cal/mol'), T0=(1,'K')),
    shortDesc = """The chemkin file reaction is R20C4H9 + O2 => C4H8Y + R3OOH""",
)

entry(
    index = 5,
    label = "C4H10 + H <=> H2 + C4H9",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(5.7e+07,'cm^3/(mol*s)'), n=2, Ea=(7700,'cal/mol'), T0=(1,'K')), Arrhenius(A=(1.8e+07,'cm^3/(mol*s)'), n=2, Ea=(5000,'cal/mol'), T0=(1,'K'))], Tmin=(0,'K'), Tmax=(0,'K'), Pmin=(0,'Pa'), Pmax=(0,'Pa')),
    shortDesc = """The chemkin file reaction is C4H10 + R1H => H2 + R20C4H9""",
)

entry(
    index = 6,
    label = "C4H10 + CH3 <=> CH4 + C4H9",
    degeneracy = 1.0,
    kinetics = MultiArrhenius(arrhenius=[Arrhenius(A=(0.6,'cm^3/(mol*s)'), n=4, Ea=(8200,'cal/mol'), T0=(1,'K')), Arrhenius(A=(4e+11,'cm^3/(mol*s)'), n=0, Ea=(9600,'cal/mol'), T0=(1,'K'))], Tmin=(0,'K'), Tmax=(0,'K'), Pmin=(0,'Pa'), Pmax=(0,'Pa')),
    shortDesc = """The chemkin file reaction is C4H10 + R4CH3 => CH4 + R20C4H9""",
)

